// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package ai

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *HistoryItem) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_HistoryItem[number], err)
}

func (x *HistoryItem) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Role, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *HistoryItem) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Content, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ChatReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ChatReq[number], err)
}

func (x *ChatReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.ProjectId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ChatReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	var v HistoryItem
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.History = append(x.History, &v)
	return offset, nil
}

func (x *ChatReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Version, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ChatResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ChatResp[number], err)
}

func (x *ChatResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Content, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ValidateReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ValidateReq[number], err)
}

func (x *ValidateReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.ProjectId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ValidateReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Version, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ValidationIssue) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ValidationIssue[number], err)
}

func (x *ValidationIssue) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Message, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ValidationIssue) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Level, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ValidationIssue) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	var v string
	v, offset, err = fastpb.ReadString(buf, _type)
	if err != nil {
		return offset, err
	}
	x.NodeIds = append(x.NodeIds, v)
	return offset, err
}

func (x *ValidateResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ValidateResp[number], err)
}

func (x *ValidateResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Valid, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *ValidateResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Summary, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ValidateResp) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	var v ValidationIssue
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Issues = append(x.Issues, &v)
	return offset, nil
}

func (x *UpdatePromptReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_UpdatePromptReq[number], err)
}

func (x *UpdatePromptReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Mode = PromptMode(v)
	return offset, nil
}

func (x *UpdatePromptReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Content, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdatePromptReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Operator, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdatePromptResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_UpdatePromptResp[number], err)
}

func (x *UpdatePromptResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *UpdatePromptResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Mode = PromptMode(v)
	return offset, nil
}

func (x *UpdatePromptResp) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.UpdatedAt, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GetPromptReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GetPromptReq[number], err)
}

func (x *GetPromptReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Mode = PromptMode(v)
	return offset, nil
}

func (x *GetPromptResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GetPromptResp[number], err)
}

func (x *GetPromptResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *GetPromptResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Mode = PromptMode(v)
	return offset, nil
}

func (x *GetPromptResp) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Content, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GetPromptResp) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.UpdatedAt, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *HistoryItem) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *HistoryItem) fastWriteField1(buf []byte) (offset int) {
	if x.Role == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetRole())
	return offset
}

func (x *HistoryItem) fastWriteField2(buf []byte) (offset int) {
	if x.Content == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetContent())
	return offset
}

func (x *ChatReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *ChatReq) fastWriteField1(buf []byte) (offset int) {
	if x.ProjectId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetProjectId())
	return offset
}

func (x *ChatReq) fastWriteField2(buf []byte) (offset int) {
	if x.History == nil {
		return offset
	}
	for i := range x.GetHistory() {
		offset += fastpb.WriteMessage(buf[offset:], 2, x.GetHistory()[i])
	}
	return offset
}

func (x *ChatReq) fastWriteField3(buf []byte) (offset int) {
	if x.Version == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetVersion())
	return offset
}

func (x *ChatResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *ChatResp) fastWriteField1(buf []byte) (offset int) {
	if x.Content == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetContent())
	return offset
}

func (x *ValidateReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *ValidateReq) fastWriteField1(buf []byte) (offset int) {
	if x.ProjectId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetProjectId())
	return offset
}

func (x *ValidateReq) fastWriteField2(buf []byte) (offset int) {
	if x.Version == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetVersion())
	return offset
}

func (x *ValidationIssue) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *ValidationIssue) fastWriteField1(buf []byte) (offset int) {
	if x.Message == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetMessage())
	return offset
}

func (x *ValidationIssue) fastWriteField2(buf []byte) (offset int) {
	if x.Level == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetLevel())
	return offset
}

func (x *ValidationIssue) fastWriteField3(buf []byte) (offset int) {
	if len(x.NodeIds) == 0 {
		return offset
	}
	for i := range x.GetNodeIds() {
		offset += fastpb.WriteString(buf[offset:], 3, x.GetNodeIds()[i])
	}
	return offset
}

func (x *ValidateResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *ValidateResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Valid {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetValid())
	return offset
}

func (x *ValidateResp) fastWriteField2(buf []byte) (offset int) {
	if x.Summary == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetSummary())
	return offset
}

func (x *ValidateResp) fastWriteField3(buf []byte) (offset int) {
	if x.Issues == nil {
		return offset
	}
	for i := range x.GetIssues() {
		offset += fastpb.WriteMessage(buf[offset:], 3, x.GetIssues()[i])
	}
	return offset
}

func (x *UpdatePromptReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *UpdatePromptReq) fastWriteField1(buf []byte) (offset int) {
	if x.Mode == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 1, int32(x.GetMode()))
	return offset
}

func (x *UpdatePromptReq) fastWriteField2(buf []byte) (offset int) {
	if x.Content == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetContent())
	return offset
}

func (x *UpdatePromptReq) fastWriteField3(buf []byte) (offset int) {
	if x.Operator == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetOperator())
	return offset
}

func (x *UpdatePromptResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *UpdatePromptResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *UpdatePromptResp) fastWriteField2(buf []byte) (offset int) {
	if x.Mode == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 2, int32(x.GetMode()))
	return offset
}

func (x *UpdatePromptResp) fastWriteField3(buf []byte) (offset int) {
	if x.UpdatedAt == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetUpdatedAt())
	return offset
}

func (x *GetPromptReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *GetPromptReq) fastWriteField1(buf []byte) (offset int) {
	if x.Mode == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 1, int32(x.GetMode()))
	return offset
}

func (x *GetPromptResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *GetPromptResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *GetPromptResp) fastWriteField2(buf []byte) (offset int) {
	if x.Mode == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 2, int32(x.GetMode()))
	return offset
}

func (x *GetPromptResp) fastWriteField3(buf []byte) (offset int) {
	if x.Content == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetContent())
	return offset
}

func (x *GetPromptResp) fastWriteField4(buf []byte) (offset int) {
	if x.UpdatedAt == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetUpdatedAt())
	return offset
}

func (x *HistoryItem) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *HistoryItem) sizeField1() (n int) {
	if x.Role == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetRole())
	return n
}

func (x *HistoryItem) sizeField2() (n int) {
	if x.Content == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetContent())
	return n
}

func (x *ChatReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *ChatReq) sizeField1() (n int) {
	if x.ProjectId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetProjectId())
	return n
}

func (x *ChatReq) sizeField2() (n int) {
	if x.History == nil {
		return n
	}
	for i := range x.GetHistory() {
		n += fastpb.SizeMessage(2, x.GetHistory()[i])
	}
	return n
}

func (x *ChatReq) sizeField3() (n int) {
	if x.Version == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetVersion())
	return n
}

func (x *ChatResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *ChatResp) sizeField1() (n int) {
	if x.Content == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetContent())
	return n
}

func (x *ValidateReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *ValidateReq) sizeField1() (n int) {
	if x.ProjectId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetProjectId())
	return n
}

func (x *ValidateReq) sizeField2() (n int) {
	if x.Version == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetVersion())
	return n
}

func (x *ValidationIssue) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *ValidationIssue) sizeField1() (n int) {
	if x.Message == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetMessage())
	return n
}

func (x *ValidationIssue) sizeField2() (n int) {
	if x.Level == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetLevel())
	return n
}

func (x *ValidationIssue) sizeField3() (n int) {
	if len(x.NodeIds) == 0 {
		return n
	}
	for i := range x.GetNodeIds() {
		n += fastpb.SizeString(3, x.GetNodeIds()[i])
	}
	return n
}

func (x *ValidateResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *ValidateResp) sizeField1() (n int) {
	if !x.Valid {
		return n
	}
	n += fastpb.SizeBool(1, x.GetValid())
	return n
}

func (x *ValidateResp) sizeField2() (n int) {
	if x.Summary == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetSummary())
	return n
}

func (x *ValidateResp) sizeField3() (n int) {
	if x.Issues == nil {
		return n
	}
	for i := range x.GetIssues() {
		n += fastpb.SizeMessage(3, x.GetIssues()[i])
	}
	return n
}

func (x *UpdatePromptReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *UpdatePromptReq) sizeField1() (n int) {
	if x.Mode == 0 {
		return n
	}
	n += fastpb.SizeInt32(1, int32(x.GetMode()))
	return n
}

func (x *UpdatePromptReq) sizeField2() (n int) {
	if x.Content == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetContent())
	return n
}

func (x *UpdatePromptReq) sizeField3() (n int) {
	if x.Operator == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetOperator())
	return n
}

func (x *UpdatePromptResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *UpdatePromptResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *UpdatePromptResp) sizeField2() (n int) {
	if x.Mode == 0 {
		return n
	}
	n += fastpb.SizeInt32(2, int32(x.GetMode()))
	return n
}

func (x *UpdatePromptResp) sizeField3() (n int) {
	if x.UpdatedAt == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetUpdatedAt())
	return n
}

func (x *GetPromptReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *GetPromptReq) sizeField1() (n int) {
	if x.Mode == 0 {
		return n
	}
	n += fastpb.SizeInt32(1, int32(x.GetMode()))
	return n
}

func (x *GetPromptResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *GetPromptResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *GetPromptResp) sizeField2() (n int) {
	if x.Mode == 0 {
		return n
	}
	n += fastpb.SizeInt32(2, int32(x.GetMode()))
	return n
}

func (x *GetPromptResp) sizeField3() (n int) {
	if x.Content == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetContent())
	return n
}

func (x *GetPromptResp) sizeField4() (n int) {
	if x.UpdatedAt == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetUpdatedAt())
	return n
}

var fieldIDToName_HistoryItem = map[int32]string{
	1: "Role",
	2: "Content",
}

var fieldIDToName_ChatReq = map[int32]string{
	1: "ProjectId",
	2: "History",
	3: "Version",
}

var fieldIDToName_ChatResp = map[int32]string{
	1: "Content",
}

var fieldIDToName_ValidateReq = map[int32]string{
	1: "ProjectId",
	2: "Version",
}

var fieldIDToName_ValidationIssue = map[int32]string{
	1: "Message",
	2: "Level",
	3: "NodeIds",
}

var fieldIDToName_ValidateResp = map[int32]string{
	1: "Valid",
	2: "Summary",
	3: "Issues",
}

var fieldIDToName_UpdatePromptReq = map[int32]string{
	1: "Mode",
	2: "Content",
	3: "Operator",
}

var fieldIDToName_UpdatePromptResp = map[int32]string{
	1: "Success",
	2: "Mode",
	3: "UpdatedAt",
}

var fieldIDToName_GetPromptReq = map[int32]string{
	1: "Mode",
}

var fieldIDToName_GetPromptResp = map[int32]string{
	1: "Success",
	2: "Mode",
	3: "Content",
	4: "UpdatedAt",
}
