// Code generated by Kitex v0.9.1. DO NOT EDIT.

package documentservice

import (
	"context"
	document "github.com/MoScenix/industrial-fault-tree-ai/rpc_gen/kitex_gen/document"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ParsePersonalPDF(ctx context.Context, Req *document.ParsePersonalPDFReq, callOptions ...callopt.Option) (r *document.ParsePDFResp, err error)
	ParseProjectPDF(ctx context.Context, Req *document.ParseProjectPDFReq, callOptions ...callopt.Option) (r *document.ParsePDFResp, err error)
	GetDocument(ctx context.Context, Req *document.GetDocumentReq, callOptions ...callopt.Option) (r *document.GetDocumentResp, err error)
	ListDocuments(ctx context.Context, Req *document.ListDocumentsReq, callOptions ...callopt.Option) (r *document.ListDocumentsResp, err error)
	SearchDocuments(ctx context.Context, Req *document.SearchDocumentsReq, callOptions ...callopt.Option) (r *document.SearchDocumentsResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kDocumentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDocumentServiceClient struct {
	*kClient
}

func (p *kDocumentServiceClient) ParsePersonalPDF(ctx context.Context, Req *document.ParsePersonalPDFReq, callOptions ...callopt.Option) (r *document.ParsePDFResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ParsePersonalPDF(ctx, Req)
}

func (p *kDocumentServiceClient) ParseProjectPDF(ctx context.Context, Req *document.ParseProjectPDFReq, callOptions ...callopt.Option) (r *document.ParsePDFResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ParseProjectPDF(ctx, Req)
}

func (p *kDocumentServiceClient) GetDocument(ctx context.Context, Req *document.GetDocumentReq, callOptions ...callopt.Option) (r *document.GetDocumentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDocument(ctx, Req)
}

func (p *kDocumentServiceClient) ListDocuments(ctx context.Context, Req *document.ListDocumentsReq, callOptions ...callopt.Option) (r *document.ListDocumentsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListDocuments(ctx, Req)
}

func (p *kDocumentServiceClient) SearchDocuments(ctx context.Context, Req *document.SearchDocumentsReq, callOptions ...callopt.Option) (r *document.SearchDocumentsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchDocuments(ctx, Req)
}
