// Code generated by Kitex v0.9.1. DO NOT EDIT.

package documentservice

import (
	"context"
	"errors"
	document "github.com/MoScenix/industrial-fault-tree-ai/rpc_gen/kitex_gen/document"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ParsePersonalPDF": kitex.NewMethodInfo(
		parsePersonalPDFHandler,
		newParsePersonalPDFArgs,
		newParsePersonalPDFResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ParseProjectPDF": kitex.NewMethodInfo(
		parseProjectPDFHandler,
		newParseProjectPDFArgs,
		newParseProjectPDFResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetDocument": kitex.NewMethodInfo(
		getDocumentHandler,
		newGetDocumentArgs,
		newGetDocumentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListDocuments": kitex.NewMethodInfo(
		listDocumentsHandler,
		newListDocumentsArgs,
		newListDocumentsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SearchDocuments": kitex.NewMethodInfo(
		searchDocumentsHandler,
		newSearchDocumentsArgs,
		newSearchDocumentsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	documentServiceServiceInfo                = NewServiceInfo()
	documentServiceServiceInfoForClient       = NewServiceInfoForClient()
	documentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return documentServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return documentServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return documentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "DocumentService"
	handlerType := (*document.DocumentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "document",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func parsePersonalPDFHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(document.ParsePersonalPDFReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(document.DocumentService).ParsePersonalPDF(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ParsePersonalPDFArgs:
		success, err := handler.(document.DocumentService).ParsePersonalPDF(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ParsePersonalPDFResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newParsePersonalPDFArgs() interface{} {
	return &ParsePersonalPDFArgs{}
}

func newParsePersonalPDFResult() interface{} {
	return &ParsePersonalPDFResult{}
}

type ParsePersonalPDFArgs struct {
	Req *document.ParsePersonalPDFReq
}

func (p *ParsePersonalPDFArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(document.ParsePersonalPDFReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ParsePersonalPDFArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ParsePersonalPDFArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ParsePersonalPDFArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ParsePersonalPDFArgs) Unmarshal(in []byte) error {
	msg := new(document.ParsePersonalPDFReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ParsePersonalPDFArgs_Req_DEFAULT *document.ParsePersonalPDFReq

func (p *ParsePersonalPDFArgs) GetReq() *document.ParsePersonalPDFReq {
	if !p.IsSetReq() {
		return ParsePersonalPDFArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ParsePersonalPDFArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ParsePersonalPDFArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ParsePersonalPDFResult struct {
	Success *document.ParsePDFResp
}

var ParsePersonalPDFResult_Success_DEFAULT *document.ParsePDFResp

func (p *ParsePersonalPDFResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(document.ParsePDFResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ParsePersonalPDFResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ParsePersonalPDFResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ParsePersonalPDFResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ParsePersonalPDFResult) Unmarshal(in []byte) error {
	msg := new(document.ParsePDFResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ParsePersonalPDFResult) GetSuccess() *document.ParsePDFResp {
	if !p.IsSetSuccess() {
		return ParsePersonalPDFResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ParsePersonalPDFResult) SetSuccess(x interface{}) {
	p.Success = x.(*document.ParsePDFResp)
}

func (p *ParsePersonalPDFResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ParsePersonalPDFResult) GetResult() interface{} {
	return p.Success
}

func parseProjectPDFHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(document.ParseProjectPDFReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(document.DocumentService).ParseProjectPDF(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ParseProjectPDFArgs:
		success, err := handler.(document.DocumentService).ParseProjectPDF(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ParseProjectPDFResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newParseProjectPDFArgs() interface{} {
	return &ParseProjectPDFArgs{}
}

func newParseProjectPDFResult() interface{} {
	return &ParseProjectPDFResult{}
}

type ParseProjectPDFArgs struct {
	Req *document.ParseProjectPDFReq
}

func (p *ParseProjectPDFArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(document.ParseProjectPDFReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ParseProjectPDFArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ParseProjectPDFArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ParseProjectPDFArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ParseProjectPDFArgs) Unmarshal(in []byte) error {
	msg := new(document.ParseProjectPDFReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ParseProjectPDFArgs_Req_DEFAULT *document.ParseProjectPDFReq

func (p *ParseProjectPDFArgs) GetReq() *document.ParseProjectPDFReq {
	if !p.IsSetReq() {
		return ParseProjectPDFArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ParseProjectPDFArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ParseProjectPDFArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ParseProjectPDFResult struct {
	Success *document.ParsePDFResp
}

var ParseProjectPDFResult_Success_DEFAULT *document.ParsePDFResp

func (p *ParseProjectPDFResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(document.ParsePDFResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ParseProjectPDFResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ParseProjectPDFResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ParseProjectPDFResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ParseProjectPDFResult) Unmarshal(in []byte) error {
	msg := new(document.ParsePDFResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ParseProjectPDFResult) GetSuccess() *document.ParsePDFResp {
	if !p.IsSetSuccess() {
		return ParseProjectPDFResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ParseProjectPDFResult) SetSuccess(x interface{}) {
	p.Success = x.(*document.ParsePDFResp)
}

func (p *ParseProjectPDFResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ParseProjectPDFResult) GetResult() interface{} {
	return p.Success
}

func getDocumentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(document.GetDocumentReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(document.DocumentService).GetDocument(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetDocumentArgs:
		success, err := handler.(document.DocumentService).GetDocument(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetDocumentResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetDocumentArgs() interface{} {
	return &GetDocumentArgs{}
}

func newGetDocumentResult() interface{} {
	return &GetDocumentResult{}
}

type GetDocumentArgs struct {
	Req *document.GetDocumentReq
}

func (p *GetDocumentArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(document.GetDocumentReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetDocumentArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetDocumentArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetDocumentArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetDocumentArgs) Unmarshal(in []byte) error {
	msg := new(document.GetDocumentReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetDocumentArgs_Req_DEFAULT *document.GetDocumentReq

func (p *GetDocumentArgs) GetReq() *document.GetDocumentReq {
	if !p.IsSetReq() {
		return GetDocumentArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetDocumentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetDocumentArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetDocumentResult struct {
	Success *document.GetDocumentResp
}

var GetDocumentResult_Success_DEFAULT *document.GetDocumentResp

func (p *GetDocumentResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(document.GetDocumentResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetDocumentResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetDocumentResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetDocumentResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetDocumentResult) Unmarshal(in []byte) error {
	msg := new(document.GetDocumentResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetDocumentResult) GetSuccess() *document.GetDocumentResp {
	if !p.IsSetSuccess() {
		return GetDocumentResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetDocumentResult) SetSuccess(x interface{}) {
	p.Success = x.(*document.GetDocumentResp)
}

func (p *GetDocumentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetDocumentResult) GetResult() interface{} {
	return p.Success
}

func listDocumentsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(document.ListDocumentsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(document.DocumentService).ListDocuments(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListDocumentsArgs:
		success, err := handler.(document.DocumentService).ListDocuments(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListDocumentsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListDocumentsArgs() interface{} {
	return &ListDocumentsArgs{}
}

func newListDocumentsResult() interface{} {
	return &ListDocumentsResult{}
}

type ListDocumentsArgs struct {
	Req *document.ListDocumentsReq
}

func (p *ListDocumentsArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(document.ListDocumentsReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListDocumentsArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListDocumentsArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListDocumentsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListDocumentsArgs) Unmarshal(in []byte) error {
	msg := new(document.ListDocumentsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListDocumentsArgs_Req_DEFAULT *document.ListDocumentsReq

func (p *ListDocumentsArgs) GetReq() *document.ListDocumentsReq {
	if !p.IsSetReq() {
		return ListDocumentsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListDocumentsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListDocumentsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListDocumentsResult struct {
	Success *document.ListDocumentsResp
}

var ListDocumentsResult_Success_DEFAULT *document.ListDocumentsResp

func (p *ListDocumentsResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(document.ListDocumentsResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListDocumentsResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListDocumentsResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListDocumentsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListDocumentsResult) Unmarshal(in []byte) error {
	msg := new(document.ListDocumentsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListDocumentsResult) GetSuccess() *document.ListDocumentsResp {
	if !p.IsSetSuccess() {
		return ListDocumentsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListDocumentsResult) SetSuccess(x interface{}) {
	p.Success = x.(*document.ListDocumentsResp)
}

func (p *ListDocumentsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListDocumentsResult) GetResult() interface{} {
	return p.Success
}

func searchDocumentsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(document.SearchDocumentsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(document.DocumentService).SearchDocuments(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SearchDocumentsArgs:
		success, err := handler.(document.DocumentService).SearchDocuments(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SearchDocumentsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSearchDocumentsArgs() interface{} {
	return &SearchDocumentsArgs{}
}

func newSearchDocumentsResult() interface{} {
	return &SearchDocumentsResult{}
}

type SearchDocumentsArgs struct {
	Req *document.SearchDocumentsReq
}

func (p *SearchDocumentsArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(document.SearchDocumentsReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SearchDocumentsArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SearchDocumentsArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SearchDocumentsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SearchDocumentsArgs) Unmarshal(in []byte) error {
	msg := new(document.SearchDocumentsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SearchDocumentsArgs_Req_DEFAULT *document.SearchDocumentsReq

func (p *SearchDocumentsArgs) GetReq() *document.SearchDocumentsReq {
	if !p.IsSetReq() {
		return SearchDocumentsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SearchDocumentsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchDocumentsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SearchDocumentsResult struct {
	Success *document.SearchDocumentsResp
}

var SearchDocumentsResult_Success_DEFAULT *document.SearchDocumentsResp

func (p *SearchDocumentsResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(document.SearchDocumentsResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SearchDocumentsResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SearchDocumentsResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SearchDocumentsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SearchDocumentsResult) Unmarshal(in []byte) error {
	msg := new(document.SearchDocumentsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SearchDocumentsResult) GetSuccess() *document.SearchDocumentsResp {
	if !p.IsSetSuccess() {
		return SearchDocumentsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SearchDocumentsResult) SetSuccess(x interface{}) {
	p.Success = x.(*document.SearchDocumentsResp)
}

func (p *SearchDocumentsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchDocumentsResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ParsePersonalPDF(ctx context.Context, Req *document.ParsePersonalPDFReq) (r *document.ParsePDFResp, err error) {
	var _args ParsePersonalPDFArgs
	_args.Req = Req
	var _result ParsePersonalPDFResult
	if err = p.c.Call(ctx, "ParsePersonalPDF", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ParseProjectPDF(ctx context.Context, Req *document.ParseProjectPDFReq) (r *document.ParsePDFResp, err error) {
	var _args ParseProjectPDFArgs
	_args.Req = Req
	var _result ParseProjectPDFResult
	if err = p.c.Call(ctx, "ParseProjectPDF", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetDocument(ctx context.Context, Req *document.GetDocumentReq) (r *document.GetDocumentResp, err error) {
	var _args GetDocumentArgs
	_args.Req = Req
	var _result GetDocumentResult
	if err = p.c.Call(ctx, "GetDocument", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListDocuments(ctx context.Context, Req *document.ListDocumentsReq) (r *document.ListDocumentsResp, err error) {
	var _args ListDocumentsArgs
	_args.Req = Req
	var _result ListDocumentsResult
	if err = p.c.Call(ctx, "ListDocuments", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchDocuments(ctx context.Context, Req *document.SearchDocumentsReq) (r *document.SearchDocumentsResp, err error) {
	var _args SearchDocumentsArgs
	_args.Req = Req
	var _result SearchDocumentsResult
	if err = p.c.Call(ctx, "SearchDocuments", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
