FROM golang:1.25.5

WORKDIR /usr/src/industrial-fault-tree-ai

ENV GOPROXY=https://goproxy.cn,direct
ENV GOSUMDB=off

COPY common/go.mod common/go.sum ./common/
COPY rpc_gen/go.mod rpc_gen/go.sum ./rpc_gen/
COPY app/ai/go.mod app/ai/go.sum ./app/ai/

WORKDIR /usr/src/industrial-fault-tree-ai/app/ai
RUN go mod download

WORKDIR /usr/src/industrial-fault-tree-ai
COPY rpc_gen ./rpc_gen
COPY common ./common

COPY app/ai ./app/ai

RUN cd app/ai && go build -v -o server

WORKDIR /usr/src/industrial-fault-tree-ai/app/ai
EXPOSE 8891
CMD ["./server"]
