FROM golang:1.25.5

WORKDIR /usr/src/industrial-fault-tree-ai

ENV GOPROXY=https://goproxy.cn,https://proxy.golang.org,direct
ENV GOSUMDB=sum.golang.google.cn

COPY app/graph/go.mod app/graph/go.sum ./app/graph/
COPY rpc_gen ./rpc_gen
COPY common ./common

RUN cd app/graph && go mod download && go mod verify

COPY app/graph ./app/graph

RUN cd app/graph && go build -v -o server

WORKDIR /usr/src/industrial-fault-tree-ai/app/graph
EXPOSE 8890
CMD ["./server"]
