FROM golang:1.25.5

WORKDIR /usr/src/industrial-fault-tree-ai

ENV GOPROXY=https://goproxy.cn,direct
ENV GOSUMDB=off

COPY common/go.mod common/go.sum ./common/
COPY rpc_gen/go.mod rpc_gen/go.sum ./rpc_gen/
COPY app/user/go.mod app/user/go.sum ./app/user/

WORKDIR /usr/src/industrial-fault-tree-ai
COPY rpc_gen ./rpc_gen
COPY common ./common

COPY app/user ./app/user

RUN cd app/user && go build -v -o server

WORKDIR /usr/src/industrial-fault-tree-ai/app/user
EXPOSE 8888
CMD ["./server"]
