FROM golang:1.25.5

WORKDIR /usr/src/industrial-fault-tree-ai

ENV GOPROXY=https://goproxy.cn,https://proxy.golang.org,direct
ENV GOSUMDB=sum.golang.google.cn

COPY app/document/go.mod app/document/go.sum ./app/document/
COPY rpc_gen ./rpc_gen
COPY common ./common

RUN cd app/document && go mod download && go mod verify

COPY app/document ./app/document

RUN cd app/document && go build -v -o server

WORKDIR /usr/src/industrial-fault-tree-ai/app/document
EXPOSE 8892
CMD ["./server"]
