FROM golang:1.25.5

WORKDIR /usr/src/industrial-fault-tree-ai

ENV GOPROXY=https://goproxy.cn,https://proxy.golang.org,direct
ENV GOSUMDB=sum.golang.google.cn

COPY app/ai/go.mod app/ai/go.sum ./app/ai/
COPY rpc_gen ./rpc_gen
COPY common ./common

RUN cd app/ai && go mod download && go mod verify

COPY app/ai ./app/ai

RUN cd app/ai && go build -v -o server

WORKDIR /usr/src/industrial-fault-tree-ai/app/ai
EXPOSE 8891
CMD ["./server"]
