// Code generated by hertz generator.

package ai

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _aiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _promptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpromptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepromptMw() []app.HandlerFunc {
	// your code...
	return nil
}
