// Code generated by Kitex v0.9.1. DO NOT EDIT.

package aiservice

import (
	"context"
	"errors"
	"fmt"
	ai "github.com/MoScenix/industrial-fault-tree-ai/rpc_gen/kitex_gen/ai"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Chat": kitex.NewMethodInfo(
		chatHandler,
		newChatArgs,
		newChatResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
	"Validate": kitex.NewMethodInfo(
		validateHandler,
		newValidateArgs,
		newValidateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdatePrompt": kitex.NewMethodInfo(
		updatePromptHandler,
		newUpdatePromptArgs,
		newUpdatePromptResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	aiServiceServiceInfo                = NewServiceInfo()
	aiServiceServiceInfoForClient       = NewServiceInfoForClient()
	aiServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return aiServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return aiServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return aiServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(true, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AiService"
	handlerType := (*ai.AiService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "ai",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func chatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	streamingArgs, ok := arg.(*streaming.Args)
	if !ok {
		return errInvalidMessageType
	}
	st := streamingArgs.Stream
	stream := &aiServiceChatServer{st}
	req := new(ai.ChatReq)
	if err := st.RecvMsg(req); err != nil {
		return err
	}
	return handler.(ai.AiService).Chat(req, stream)
}

type aiServiceChatClient struct {
	streaming.Stream
}

func (x *aiServiceChatClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *aiServiceChatClient) Recv() (*ai.ChatResp, error) {
	m := new(ai.ChatResp)
	return m, x.Stream.RecvMsg(m)
}

type aiServiceChatServer struct {
	streaming.Stream
}

func (x *aiServiceChatServer) Send(m *ai.ChatResp) error {
	return x.Stream.SendMsg(m)
}

func newChatArgs() interface{} {
	return &ChatArgs{}
}

func newChatResult() interface{} {
	return &ChatResult{}
}

type ChatArgs struct {
	Req *ai.ChatReq
}

func (p *ChatArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(ai.ChatReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ChatArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ChatArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ChatArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ChatArgs) Unmarshal(in []byte) error {
	msg := new(ai.ChatReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ChatArgs_Req_DEFAULT *ai.ChatReq

func (p *ChatArgs) GetReq() *ai.ChatReq {
	if !p.IsSetReq() {
		return ChatArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ChatArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ChatResult struct {
	Success *ai.ChatResp
}

var ChatResult_Success_DEFAULT *ai.ChatResp

func (p *ChatResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(ai.ChatResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ChatResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ChatResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ChatResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ChatResult) Unmarshal(in []byte) error {
	msg := new(ai.ChatResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ChatResult) GetSuccess() *ai.ChatResp {
	if !p.IsSetSuccess() {
		return ChatResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ChatResult) SetSuccess(x interface{}) {
	p.Success = x.(*ai.ChatResp)
}

func (p *ChatResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatResult) GetResult() interface{} {
	return p.Success
}

func validateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(ai.ValidateReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(ai.AiService).Validate(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ValidateArgs:
		success, err := handler.(ai.AiService).Validate(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ValidateResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newValidateArgs() interface{} {
	return &ValidateArgs{}
}

func newValidateResult() interface{} {
	return &ValidateResult{}
}

type ValidateArgs struct {
	Req *ai.ValidateReq
}

func (p *ValidateArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(ai.ValidateReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ValidateArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ValidateArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ValidateArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ValidateArgs) Unmarshal(in []byte) error {
	msg := new(ai.ValidateReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ValidateArgs_Req_DEFAULT *ai.ValidateReq

func (p *ValidateArgs) GetReq() *ai.ValidateReq {
	if !p.IsSetReq() {
		return ValidateArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ValidateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ValidateArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ValidateResult struct {
	Success *ai.ValidateResp
}

var ValidateResult_Success_DEFAULT *ai.ValidateResp

func (p *ValidateResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(ai.ValidateResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ValidateResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ValidateResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ValidateResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ValidateResult) Unmarshal(in []byte) error {
	msg := new(ai.ValidateResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ValidateResult) GetSuccess() *ai.ValidateResp {
	if !p.IsSetSuccess() {
		return ValidateResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ValidateResult) SetSuccess(x interface{}) {
	p.Success = x.(*ai.ValidateResp)
}

func (p *ValidateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ValidateResult) GetResult() interface{} {
	return p.Success
}

func updatePromptHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(ai.UpdatePromptReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(ai.AiService).UpdatePrompt(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdatePromptArgs:
		success, err := handler.(ai.AiService).UpdatePrompt(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdatePromptResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdatePromptArgs() interface{} {
	return &UpdatePromptArgs{}
}

func newUpdatePromptResult() interface{} {
	return &UpdatePromptResult{}
}

type UpdatePromptArgs struct {
	Req *ai.UpdatePromptReq
}

func (p *UpdatePromptArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(ai.UpdatePromptReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UpdatePromptArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UpdatePromptArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UpdatePromptArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdatePromptArgs) Unmarshal(in []byte) error {
	msg := new(ai.UpdatePromptReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdatePromptArgs_Req_DEFAULT *ai.UpdatePromptReq

func (p *UpdatePromptArgs) GetReq() *ai.UpdatePromptReq {
	if !p.IsSetReq() {
		return UpdatePromptArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdatePromptArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdatePromptArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdatePromptResult struct {
	Success *ai.UpdatePromptResp
}

var UpdatePromptResult_Success_DEFAULT *ai.UpdatePromptResp

func (p *UpdatePromptResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(ai.UpdatePromptResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UpdatePromptResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UpdatePromptResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UpdatePromptResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdatePromptResult) Unmarshal(in []byte) error {
	msg := new(ai.UpdatePromptResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdatePromptResult) GetSuccess() *ai.UpdatePromptResp {
	if !p.IsSetSuccess() {
		return UpdatePromptResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdatePromptResult) SetSuccess(x interface{}) {
	p.Success = x.(*ai.UpdatePromptResp)
}

func (p *UpdatePromptResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdatePromptResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Chat(ctx context.Context, req *ai.ChatReq) (AiService_ChatClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "Chat", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &aiServiceChatClient{res.Stream}

	if err := stream.Stream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := stream.Stream.Close(); err != nil {
		return nil, err
	}
	return stream, nil
}

func (p *kClient) Validate(ctx context.Context, Req *ai.ValidateReq) (r *ai.ValidateResp, err error) {
	var _args ValidateArgs
	_args.Req = Req
	var _result ValidateResult
	if err = p.c.Call(ctx, "Validate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdatePrompt(ctx context.Context, Req *ai.UpdatePromptReq) (r *ai.UpdatePromptResp, err error) {
	var _args UpdatePromptArgs
	_args.Req = Req
	var _result UpdatePromptResult
	if err = p.c.Call(ctx, "UpdatePrompt", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
