// Code generated by Kitex v0.9.1. DO NOT EDIT.

package aiservice

import (
	"context"
	ai "github.com/MoScenix/industrial-fault-tree-ai/rpc_gen/kitex_gen/ai"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
	"github.com/cloudwego/kitex/client/streamclient"
	"github.com/cloudwego/kitex/client/callopt/streamcall"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Chat(ctx context.Context, Req *ai.ChatReq, callOptions ...callopt.Option) (stream AiService_ChatClient, err error)
	Validate(ctx context.Context, Req *ai.ValidateReq, callOptions ...callopt.Option) (r *ai.ValidateResp, err error)
	UpdatePrompt(ctx context.Context, Req *ai.UpdatePromptReq, callOptions ...callopt.Option) (r *ai.UpdatePromptResp, err error)
	GetPrompt(ctx context.Context, Req *ai.GetPromptReq, callOptions ...callopt.Option) (r *ai.GetPromptResp, err error)
}

// StreamClient is designed to provide Interface for Streaming APIs.
type StreamClient interface {
	Chat(ctx context.Context, Req *ai.ChatReq, callOptions ...streamcall.Option) (stream AiService_ChatClient, err error)
}

type AiService_ChatClient interface {
	streaming.Stream
	Recv() (*ai.ChatResp, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAiServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAiServiceClient struct {
	*kClient
}

func (p *kAiServiceClient) Chat(ctx context.Context, Req *ai.ChatReq, callOptions ...callopt.Option) (stream AiService_ChatClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Chat(ctx, Req)
}

func (p *kAiServiceClient) Validate(ctx context.Context, Req *ai.ValidateReq, callOptions ...callopt.Option) (r *ai.ValidateResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Validate(ctx, Req)
}

func (p *kAiServiceClient) UpdatePrompt(ctx context.Context, Req *ai.UpdatePromptReq, callOptions ...callopt.Option) (r *ai.UpdatePromptResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdatePrompt(ctx, Req)
}

func (p *kAiServiceClient) GetPrompt(ctx context.Context, Req *ai.GetPromptReq, callOptions ...callopt.Option) (r *ai.GetPromptResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPrompt(ctx, Req)
}

// NewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
func NewStreamClient(destService string, opts ...streamclient.Option) (StreamClient, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))
	options = append(options, client.WithTransportProtocol(transport.GRPC))
	options = append(options, streamclient.GetClientOptions(opts)...)

	kc, err := client.NewClient(serviceInfoForStreamClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAiServiceStreamClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
// It panics if any error occurs.
func MustNewStreamClient(destService string, opts ...streamclient.Option) StreamClient {
	kc, err := NewStreamClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAiServiceStreamClient struct {
	*kClient
}

func (p *kAiServiceStreamClient) Chat(ctx context.Context, Req *ai.ChatReq, callOptions ...streamcall.Option) (stream AiService_ChatClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.Chat(ctx, Req)
}
