// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	ai "github.com/MoScenix/industrial-fault-tree-ai/app/bff/biz/router/ai"
	document "github.com/MoScenix/industrial-fault-tree-ai/app/bff/biz/router/document"
	graph "github.com/MoScenix/industrial-fault-tree-ai/app/bff/biz/router/graph"
	user "github.com/MoScenix/industrial-fault-tree-ai/app/bff/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	ai.Register(r)

	document.Register(r)
	graph.Register(r)
	user.Register(r)
}
