// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: ai_bff.proto

package ai

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/MoScenix/industrial-fault-tree-ai/app/bff/hertz_gen/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResponseBoolean struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code" query:"code"`
	Data    bool   `protobuf:"varint,2,opt,name=data,proto3" json:"data,omitempty" form:"data" query:"data"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
}

func (x *BaseResponseBoolean) Reset() {
	*x = BaseResponseBoolean{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_bff_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResponseBoolean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponseBoolean) ProtoMessage() {}

func (x *BaseResponseBoolean) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bff_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponseBoolean.ProtoReflect.Descriptor instead.
func (*BaseResponseBoolean) Descriptor() ([]byte, []int) {
	return file_ai_bff_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponseBoolean) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponseBoolean) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

func (x *BaseResponseBoolean) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BaseResponsePromptVO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code" query:"code"`
	Data    *PromptVO `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty" form:"data" query:"data"`
	Message string    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty" form:"message" query:"message"`
}

func (x *BaseResponsePromptVO) Reset() {
	*x = BaseResponsePromptVO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_bff_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResponsePromptVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponsePromptVO) ProtoMessage() {}

func (x *BaseResponsePromptVO) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bff_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponsePromptVO.ProtoReflect.Descriptor instead.
func (*BaseResponsePromptVO) Descriptor() ([]byte, []int) {
	return file_ai_bff_proto_rawDescGZIP(), []int{1}
}

func (x *BaseResponsePromptVO) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponsePromptVO) GetData() *PromptVO {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BaseResponsePromptVO) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPromptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode int32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty" query:"mode"`
}

func (x *GetPromptRequest) Reset() {
	*x = GetPromptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_bff_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromptRequest) ProtoMessage() {}

func (x *GetPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bff_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromptRequest.ProtoReflect.Descriptor instead.
func (*GetPromptRequest) Descriptor() ([]byte, []int) {
	return file_ai_bff_proto_rawDescGZIP(), []int{2}
}

func (x *GetPromptRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type UpdatePromptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode    int32  `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty" form:"mode" query:"mode"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty" form:"content" query:"content"`
}

func (x *UpdatePromptRequest) Reset() {
	*x = UpdatePromptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_bff_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePromptRequest) ProtoMessage() {}

func (x *UpdatePromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bff_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePromptRequest.ProtoReflect.Descriptor instead.
func (*UpdatePromptRequest) Descriptor() ([]byte, []int) {
	return file_ai_bff_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePromptRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *UpdatePromptRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PromptVO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode      int32  `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty" form:"mode" query:"mode"`
	Content   string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty" form:"content" query:"content"`
	UpdatedAt string `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" form:"updatedAt" query:"updatedAt"`
}

func (x *PromptVO) Reset() {
	*x = PromptVO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_bff_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromptVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptVO) ProtoMessage() {}

func (x *PromptVO) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bff_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptVO.ProtoReflect.Descriptor instead.
func (*PromptVO) Descriptor() ([]byte, []int) {
	return file_ai_bff_proto_rawDescGZIP(), []int{4}
}

func (x *PromptVO) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *PromptVO) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PromptVO) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_ai_bff_proto protoreflect.FileDescriptor

var file_ai_bff_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x69, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x62, 0x66, 0x66, 0x2e, 0x61, 0x69, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x57, 0x0a, 0x13, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x6a, 0x0a, 0x14, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74,
	0x56, 0x4f, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x69, 0x2e, 0x50, 0x72,
	0x6f, 0x6d, 0x70, 0x74, 0x56, 0x4f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x30, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x08, 0xb2, 0xbb, 0x18, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x43, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x56, 0x0a,
	0x08, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x56, 0x4f, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0xc5, 0x01, 0x0a, 0x09, 0x41, 0x69, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74,
	0x12, 0x18, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x62, 0x66, 0x66,
	0x2e, 0x61, 0x69, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x56, 0x4f, 0x22, 0x12, 0xca, 0xc1, 0x18, 0x0e, 0x2f, 0x61,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2f, 0x67, 0x65, 0x74, 0x12, 0x5f, 0x0a, 0x0c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x1b, 0x2e, 0x62,
	0x66, 0x66, 0x2e, 0x61, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x66, 0x66, 0x2e,
	0x61, 0x69, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x22, 0x15, 0xd2, 0xc1, 0x18, 0x11, 0x2f, 0x61, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x47, 0x5a,
	0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x6f, 0x53, 0x63,
	0x65, 0x6e, 0x69, 0x78, 0x2f, 0x69, 0x6e, 0x64, 0x75, 0x73, 0x74, 0x72, 0x69, 0x61, 0x6c, 0x2d,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x2d, 0x74, 0x72, 0x65, 0x65, 0x2d, 0x61, 0x69, 0x2f, 0x61, 0x70,
	0x70, 0x2f, 0x62, 0x66, 0x66, 0x2f, 0x68, 0x65, 0x72, 0x74, 0x7a, 0x5f, 0x67, 0x65, 0x6e, 0x2f,
	0x62, 0x66, 0x66, 0x2f, 0x61, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ai_bff_proto_rawDescOnce sync.Once
	file_ai_bff_proto_rawDescData = file_ai_bff_proto_rawDesc
)

func file_ai_bff_proto_rawDescGZIP() []byte {
	file_ai_bff_proto_rawDescOnce.Do(func() {
		file_ai_bff_proto_rawDescData = protoimpl.X.CompressGZIP(file_ai_bff_proto_rawDescData)
	})
	return file_ai_bff_proto_rawDescData
}

var file_ai_bff_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ai_bff_proto_goTypes = []interface{}{
	(*BaseResponseBoolean)(nil),  // 0: bff.ai.BaseResponseBoolean
	(*BaseResponsePromptVO)(nil), // 1: bff.ai.BaseResponsePromptVO
	(*GetPromptRequest)(nil),     // 2: bff.ai.GetPromptRequest
	(*UpdatePromptRequest)(nil),  // 3: bff.ai.UpdatePromptRequest
	(*PromptVO)(nil),             // 4: bff.ai.PromptVO
}
var file_ai_bff_proto_depIdxs = []int32{
	4, // 0: bff.ai.BaseResponsePromptVO.data:type_name -> bff.ai.PromptVO
	2, // 1: bff.ai.AiService.GetPrompt:input_type -> bff.ai.GetPromptRequest
	3, // 2: bff.ai.AiService.UpdatePrompt:input_type -> bff.ai.UpdatePromptRequest
	1, // 3: bff.ai.AiService.GetPrompt:output_type -> bff.ai.BaseResponsePromptVO
	0, // 4: bff.ai.AiService.UpdatePrompt:output_type -> bff.ai.BaseResponseBoolean
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ai_bff_proto_init() }
func file_ai_bff_proto_init() {
	if File_ai_bff_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ai_bff_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResponseBoolean); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_bff_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResponsePromptVO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_bff_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPromptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_bff_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePromptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_bff_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromptVO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ai_bff_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_bff_proto_goTypes,
		DependencyIndexes: file_ai_bff_proto_depIdxs,
		MessageInfos:      file_ai_bff_proto_msgTypes,
	}.Build()
	File_ai_bff_proto = out.File
	file_ai_bff_proto_rawDesc = nil
	file_ai_bff_proto_goTypes = nil
	file_ai_bff_proto_depIdxs = nil
}
