// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package graph

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *GraphInfo) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 8:
		offset, err = x.fastReadField8(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 9:
		offset, err = x.fastReadField9(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GraphInfo[number], err)
}

func (x *GraphInfo) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *GraphInfo) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.GraphName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GraphInfo) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Description, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GraphInfo) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Cover, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GraphInfo) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *GraphInfo) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.CurrentVersion, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GraphInfo) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	x.HasTmp, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *GraphInfo) fastReadField8(buf []byte, _type int8) (offset int, err error) {
	x.CreateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GraphInfo) fastReadField9(buf []byte, _type int8) (offset int, err error) {
	x.UpdateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GraphVersionInfo) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GraphVersionInfo[number], err)
}

func (x *GraphVersionInfo) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Version, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GraphVersionInfo) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.VersionName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GraphVersionInfo) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.IsCurrent, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *GraphVersionInfo) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.CreateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GraphVersionInfo) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.UpdateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GraphMessage) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 8:
		offset, err = x.fastReadField8(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GraphMessage[number], err)
}

func (x *GraphMessage) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *GraphMessage) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.GraphId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *GraphMessage) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *GraphMessage) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Role, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GraphMessage) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.Content, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GraphMessage) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.CreateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GraphMessage) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	x.UpdateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GraphMessage) fastReadField8(buf []byte, _type int8) (offset int, err error) {
	x.IsDelete, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AddGraphReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AddGraphReq[number], err)
}

func (x *AddGraphReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.GraphName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AddGraphReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Description, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AddGraphReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Cover, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AddGraphReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AddGraphResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AddGraphResp[number], err)
}

func (x *AddGraphResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *DeleteGraphReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DeleteGraphReq[number], err)
}

func (x *DeleteGraphReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *DeleteGraphResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DeleteGraphResp[number], err)
}

func (x *DeleteGraphResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *UpdateGraphReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_UpdateGraphReq[number], err)
}

func (x *UpdateGraphReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *UpdateGraphReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.GraphName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdateGraphReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Description, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdateGraphReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Cover, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdateGraphResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_UpdateGraphResp[number], err)
}

func (x *UpdateGraphResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *GetGraphReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GetGraphReq[number], err)
}

func (x *GetGraphReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *GetGraphResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GetGraphResp[number], err)
}

func (x *GetGraphResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v GraphInfo
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Graph = &v
	return offset, nil
}

func (x *ListGraphReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListGraphReq[number], err)
}

func (x *ListGraphReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.PageNum, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListGraphReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.PageSize, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListGraphReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.GraphName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListGraphReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListGraphResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListGraphResp[number], err)
}

func (x *ListGraphResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v GraphInfo
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.GraphList = append(x.GraphList, &v)
	return offset, nil
}

func (x *ListGraphResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Total, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *StartEditReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_StartEditReq[number], err)
}

func (x *StartEditReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.GraphId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *StartEditReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Version, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *StartEditResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_StartEditResp[number], err)
}

func (x *StartEditResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *StartEditResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.TmpReady, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *StartEditResp) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.BasedOnVersion, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *StartEditResp) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Message, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SaveReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SaveReq[number], err)
}

func (x *SaveReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.GraphId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *SaveReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.FromVersion, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SaveReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.ToVersion, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SaveReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.OperatorUserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *SaveReq) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.Remark, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SaveResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SaveResp[number], err)
}

func (x *SaveResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *SaveResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.FromVersion, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SaveResp) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.ToVersion, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SaveResp) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Message, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListGraphMessageReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListGraphMessageReq[number], err)
}

func (x *ListGraphMessageReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.GraphId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListGraphMessageReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.PageSize, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListGraphMessageReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.LastCreateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListGraphMessageResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListGraphMessageResp[number], err)
}

func (x *ListGraphMessageResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v GraphMessage
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.MessageList = append(x.MessageList, &v)
	return offset, nil
}

func (x *ListGraphMessageResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Total, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListGraphMessageResp) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.HasMore, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *AddGraphMessageReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AddGraphMessageReq[number], err)
}

func (x *AddGraphMessageReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.GraphId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AddGraphMessageReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AddGraphMessageReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Role, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AddGraphMessageReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Content, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AddGraphMessageResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AddGraphMessageResp[number], err)
}

func (x *AddGraphMessageResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CreateVersionReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CreateVersionReq[number], err)
}

func (x *CreateVersionReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.GraphId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *CreateVersionReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.VersionName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CreateVersionResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CreateVersionResp[number], err)
}

func (x *CreateVersionResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *CreateVersionResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Version, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *DeleteVersionReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DeleteVersionReq[number], err)
}

func (x *DeleteVersionReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.GraphId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *DeleteVersionReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Version, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *DeleteVersionResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DeleteVersionResp[number], err)
}

func (x *DeleteVersionResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *RenameVersionReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_RenameVersionReq[number], err)
}

func (x *RenameVersionReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.GraphId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *RenameVersionReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Version, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *RenameVersionReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.VersionName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *RenameVersionResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_RenameVersionResp[number], err)
}

func (x *RenameVersionResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *ListVersionReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListVersionReq[number], err)
}

func (x *ListVersionReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.GraphId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListVersionResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListVersionResp[number], err)
}

func (x *ListVersionResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v GraphVersionInfo
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.VersionList = append(x.VersionList, &v)
	return offset, nil
}

func (x *GraphInfo) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	offset += x.fastWriteField8(buf[offset:])
	offset += x.fastWriteField9(buf[offset:])
	return offset
}

func (x *GraphInfo) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *GraphInfo) fastWriteField2(buf []byte) (offset int) {
	if x.GraphName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetGraphName())
	return offset
}

func (x *GraphInfo) fastWriteField3(buf []byte) (offset int) {
	if x.Description == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetDescription())
	return offset
}

func (x *GraphInfo) fastWriteField4(buf []byte) (offset int) {
	if x.Cover == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetCover())
	return offset
}

func (x *GraphInfo) fastWriteField5(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 5, x.GetUserId())
	return offset
}

func (x *GraphInfo) fastWriteField6(buf []byte) (offset int) {
	if x.CurrentVersion == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 6, x.GetCurrentVersion())
	return offset
}

func (x *GraphInfo) fastWriteField7(buf []byte) (offset int) {
	if !x.HasTmp {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 7, x.GetHasTmp())
	return offset
}

func (x *GraphInfo) fastWriteField8(buf []byte) (offset int) {
	if x.CreateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 8, x.GetCreateTime())
	return offset
}

func (x *GraphInfo) fastWriteField9(buf []byte) (offset int) {
	if x.UpdateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 9, x.GetUpdateTime())
	return offset
}

func (x *GraphVersionInfo) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *GraphVersionInfo) fastWriteField1(buf []byte) (offset int) {
	if x.Version == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetVersion())
	return offset
}

func (x *GraphVersionInfo) fastWriteField2(buf []byte) (offset int) {
	if x.VersionName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetVersionName())
	return offset
}

func (x *GraphVersionInfo) fastWriteField3(buf []byte) (offset int) {
	if !x.IsCurrent {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 3, x.GetIsCurrent())
	return offset
}

func (x *GraphVersionInfo) fastWriteField4(buf []byte) (offset int) {
	if x.CreateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetCreateTime())
	return offset
}

func (x *GraphVersionInfo) fastWriteField5(buf []byte) (offset int) {
	if x.UpdateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 5, x.GetUpdateTime())
	return offset
}

func (x *GraphMessage) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	offset += x.fastWriteField8(buf[offset:])
	return offset
}

func (x *GraphMessage) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *GraphMessage) fastWriteField2(buf []byte) (offset int) {
	if x.GraphId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetGraphId())
	return offset
}

func (x *GraphMessage) fastWriteField3(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 3, x.GetUserId())
	return offset
}

func (x *GraphMessage) fastWriteField4(buf []byte) (offset int) {
	if x.Role == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetRole())
	return offset
}

func (x *GraphMessage) fastWriteField5(buf []byte) (offset int) {
	if x.Content == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 5, x.GetContent())
	return offset
}

func (x *GraphMessage) fastWriteField6(buf []byte) (offset int) {
	if x.CreateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 6, x.GetCreateTime())
	return offset
}

func (x *GraphMessage) fastWriteField7(buf []byte) (offset int) {
	if x.UpdateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 7, x.GetUpdateTime())
	return offset
}

func (x *GraphMessage) fastWriteField8(buf []byte) (offset int) {
	if x.IsDelete == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 8, x.GetIsDelete())
	return offset
}

func (x *AddGraphReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *AddGraphReq) fastWriteField1(buf []byte) (offset int) {
	if x.GraphName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetGraphName())
	return offset
}

func (x *AddGraphReq) fastWriteField2(buf []byte) (offset int) {
	if x.Description == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetDescription())
	return offset
}

func (x *AddGraphReq) fastWriteField3(buf []byte) (offset int) {
	if x.Cover == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetCover())
	return offset
}

func (x *AddGraphReq) fastWriteField4(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 4, x.GetUserId())
	return offset
}

func (x *AddGraphResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *AddGraphResp) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *DeleteGraphReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *DeleteGraphReq) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *DeleteGraphResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *DeleteGraphResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *UpdateGraphReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *UpdateGraphReq) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *UpdateGraphReq) fastWriteField2(buf []byte) (offset int) {
	if x.GraphName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetGraphName())
	return offset
}

func (x *UpdateGraphReq) fastWriteField3(buf []byte) (offset int) {
	if x.Description == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetDescription())
	return offset
}

func (x *UpdateGraphReq) fastWriteField4(buf []byte) (offset int) {
	if x.Cover == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetCover())
	return offset
}

func (x *UpdateGraphResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *UpdateGraphResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *GetGraphReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *GetGraphReq) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *GetGraphResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *GetGraphResp) fastWriteField1(buf []byte) (offset int) {
	if x.Graph == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 1, x.GetGraph())
	return offset
}

func (x *ListGraphReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *ListGraphReq) fastWriteField1(buf []byte) (offset int) {
	if x.PageNum == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetPageNum())
	return offset
}

func (x *ListGraphReq) fastWriteField2(buf []byte) (offset int) {
	if x.PageSize == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetPageSize())
	return offset
}

func (x *ListGraphReq) fastWriteField3(buf []byte) (offset int) {
	if x.GraphName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetGraphName())
	return offset
}

func (x *ListGraphReq) fastWriteField4(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 4, x.GetUserId())
	return offset
}

func (x *ListGraphResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *ListGraphResp) fastWriteField1(buf []byte) (offset int) {
	if x.GraphList == nil {
		return offset
	}
	for i := range x.GetGraphList() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetGraphList()[i])
	}
	return offset
}

func (x *ListGraphResp) fastWriteField2(buf []byte) (offset int) {
	if x.Total == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetTotal())
	return offset
}

func (x *StartEditReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *StartEditReq) fastWriteField1(buf []byte) (offset int) {
	if x.GraphId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetGraphId())
	return offset
}

func (x *StartEditReq) fastWriteField2(buf []byte) (offset int) {
	if x.Version == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetVersion())
	return offset
}

func (x *StartEditResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *StartEditResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *StartEditResp) fastWriteField2(buf []byte) (offset int) {
	if !x.TmpReady {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 2, x.GetTmpReady())
	return offset
}

func (x *StartEditResp) fastWriteField3(buf []byte) (offset int) {
	if x.BasedOnVersion == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetBasedOnVersion())
	return offset
}

func (x *StartEditResp) fastWriteField4(buf []byte) (offset int) {
	if x.Message == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetMessage())
	return offset
}

func (x *SaveReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *SaveReq) fastWriteField1(buf []byte) (offset int) {
	if x.GraphId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetGraphId())
	return offset
}

func (x *SaveReq) fastWriteField2(buf []byte) (offset int) {
	if x.FromVersion == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetFromVersion())
	return offset
}

func (x *SaveReq) fastWriteField3(buf []byte) (offset int) {
	if x.ToVersion == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetToVersion())
	return offset
}

func (x *SaveReq) fastWriteField4(buf []byte) (offset int) {
	if x.OperatorUserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 4, x.GetOperatorUserId())
	return offset
}

func (x *SaveReq) fastWriteField5(buf []byte) (offset int) {
	if x.Remark == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 5, x.GetRemark())
	return offset
}

func (x *SaveResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *SaveResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *SaveResp) fastWriteField2(buf []byte) (offset int) {
	if x.FromVersion == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetFromVersion())
	return offset
}

func (x *SaveResp) fastWriteField3(buf []byte) (offset int) {
	if x.ToVersion == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetToVersion())
	return offset
}

func (x *SaveResp) fastWriteField4(buf []byte) (offset int) {
	if x.Message == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetMessage())
	return offset
}

func (x *ListGraphMessageReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *ListGraphMessageReq) fastWriteField1(buf []byte) (offset int) {
	if x.GraphId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetGraphId())
	return offset
}

func (x *ListGraphMessageReq) fastWriteField2(buf []byte) (offset int) {
	if x.PageSize == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetPageSize())
	return offset
}

func (x *ListGraphMessageReq) fastWriteField3(buf []byte) (offset int) {
	if x.LastCreateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetLastCreateTime())
	return offset
}

func (x *ListGraphMessageResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *ListGraphMessageResp) fastWriteField1(buf []byte) (offset int) {
	if x.MessageList == nil {
		return offset
	}
	for i := range x.GetMessageList() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetMessageList()[i])
	}
	return offset
}

func (x *ListGraphMessageResp) fastWriteField2(buf []byte) (offset int) {
	if x.Total == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetTotal())
	return offset
}

func (x *ListGraphMessageResp) fastWriteField3(buf []byte) (offset int) {
	if !x.HasMore {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 3, x.GetHasMore())
	return offset
}

func (x *AddGraphMessageReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *AddGraphMessageReq) fastWriteField1(buf []byte) (offset int) {
	if x.GraphId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetGraphId())
	return offset
}

func (x *AddGraphMessageReq) fastWriteField2(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetUserId())
	return offset
}

func (x *AddGraphMessageReq) fastWriteField3(buf []byte) (offset int) {
	if x.Role == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetRole())
	return offset
}

func (x *AddGraphMessageReq) fastWriteField4(buf []byte) (offset int) {
	if x.Content == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetContent())
	return offset
}

func (x *AddGraphMessageResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *AddGraphMessageResp) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *CreateVersionReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *CreateVersionReq) fastWriteField1(buf []byte) (offset int) {
	if x.GraphId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetGraphId())
	return offset
}

func (x *CreateVersionReq) fastWriteField2(buf []byte) (offset int) {
	if x.VersionName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetVersionName())
	return offset
}

func (x *CreateVersionResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *CreateVersionResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *CreateVersionResp) fastWriteField2(buf []byte) (offset int) {
	if x.Version == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetVersion())
	return offset
}

func (x *DeleteVersionReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *DeleteVersionReq) fastWriteField1(buf []byte) (offset int) {
	if x.GraphId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetGraphId())
	return offset
}

func (x *DeleteVersionReq) fastWriteField2(buf []byte) (offset int) {
	if x.Version == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetVersion())
	return offset
}

func (x *DeleteVersionResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *DeleteVersionResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *RenameVersionReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *RenameVersionReq) fastWriteField1(buf []byte) (offset int) {
	if x.GraphId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetGraphId())
	return offset
}

func (x *RenameVersionReq) fastWriteField2(buf []byte) (offset int) {
	if x.Version == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetVersion())
	return offset
}

func (x *RenameVersionReq) fastWriteField3(buf []byte) (offset int) {
	if x.VersionName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetVersionName())
	return offset
}

func (x *RenameVersionResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *RenameVersionResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *ListVersionReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *ListVersionReq) fastWriteField1(buf []byte) (offset int) {
	if x.GraphId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetGraphId())
	return offset
}

func (x *ListVersionResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *ListVersionResp) fastWriteField1(buf []byte) (offset int) {
	if x.VersionList == nil {
		return offset
	}
	for i := range x.GetVersionList() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetVersionList()[i])
	}
	return offset
}

func (x *GraphInfo) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	n += x.sizeField6()
	n += x.sizeField7()
	n += x.sizeField8()
	n += x.sizeField9()
	return n
}

func (x *GraphInfo) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *GraphInfo) sizeField2() (n int) {
	if x.GraphName == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetGraphName())
	return n
}

func (x *GraphInfo) sizeField3() (n int) {
	if x.Description == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetDescription())
	return n
}

func (x *GraphInfo) sizeField4() (n int) {
	if x.Cover == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetCover())
	return n
}

func (x *GraphInfo) sizeField5() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(5, x.GetUserId())
	return n
}

func (x *GraphInfo) sizeField6() (n int) {
	if x.CurrentVersion == "" {
		return n
	}
	n += fastpb.SizeString(6, x.GetCurrentVersion())
	return n
}

func (x *GraphInfo) sizeField7() (n int) {
	if !x.HasTmp {
		return n
	}
	n += fastpb.SizeBool(7, x.GetHasTmp())
	return n
}

func (x *GraphInfo) sizeField8() (n int) {
	if x.CreateTime == "" {
		return n
	}
	n += fastpb.SizeString(8, x.GetCreateTime())
	return n
}

func (x *GraphInfo) sizeField9() (n int) {
	if x.UpdateTime == "" {
		return n
	}
	n += fastpb.SizeString(9, x.GetUpdateTime())
	return n
}

func (x *GraphVersionInfo) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *GraphVersionInfo) sizeField1() (n int) {
	if x.Version == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetVersion())
	return n
}

func (x *GraphVersionInfo) sizeField2() (n int) {
	if x.VersionName == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetVersionName())
	return n
}

func (x *GraphVersionInfo) sizeField3() (n int) {
	if !x.IsCurrent {
		return n
	}
	n += fastpb.SizeBool(3, x.GetIsCurrent())
	return n
}

func (x *GraphVersionInfo) sizeField4() (n int) {
	if x.CreateTime == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetCreateTime())
	return n
}

func (x *GraphVersionInfo) sizeField5() (n int) {
	if x.UpdateTime == "" {
		return n
	}
	n += fastpb.SizeString(5, x.GetUpdateTime())
	return n
}

func (x *GraphMessage) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	n += x.sizeField6()
	n += x.sizeField7()
	n += x.sizeField8()
	return n
}

func (x *GraphMessage) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *GraphMessage) sizeField2() (n int) {
	if x.GraphId == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetGraphId())
	return n
}

func (x *GraphMessage) sizeField3() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(3, x.GetUserId())
	return n
}

func (x *GraphMessage) sizeField4() (n int) {
	if x.Role == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetRole())
	return n
}

func (x *GraphMessage) sizeField5() (n int) {
	if x.Content == "" {
		return n
	}
	n += fastpb.SizeString(5, x.GetContent())
	return n
}

func (x *GraphMessage) sizeField6() (n int) {
	if x.CreateTime == "" {
		return n
	}
	n += fastpb.SizeString(6, x.GetCreateTime())
	return n
}

func (x *GraphMessage) sizeField7() (n int) {
	if x.UpdateTime == "" {
		return n
	}
	n += fastpb.SizeString(7, x.GetUpdateTime())
	return n
}

func (x *GraphMessage) sizeField8() (n int) {
	if x.IsDelete == 0 {
		return n
	}
	n += fastpb.SizeInt64(8, x.GetIsDelete())
	return n
}

func (x *AddGraphReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *AddGraphReq) sizeField1() (n int) {
	if x.GraphName == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetGraphName())
	return n
}

func (x *AddGraphReq) sizeField2() (n int) {
	if x.Description == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetDescription())
	return n
}

func (x *AddGraphReq) sizeField3() (n int) {
	if x.Cover == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetCover())
	return n
}

func (x *AddGraphReq) sizeField4() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(4, x.GetUserId())
	return n
}

func (x *AddGraphResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *AddGraphResp) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *DeleteGraphReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *DeleteGraphReq) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *DeleteGraphResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *DeleteGraphResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *UpdateGraphReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *UpdateGraphReq) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *UpdateGraphReq) sizeField2() (n int) {
	if x.GraphName == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetGraphName())
	return n
}

func (x *UpdateGraphReq) sizeField3() (n int) {
	if x.Description == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetDescription())
	return n
}

func (x *UpdateGraphReq) sizeField4() (n int) {
	if x.Cover == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetCover())
	return n
}

func (x *UpdateGraphResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *UpdateGraphResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *GetGraphReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *GetGraphReq) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *GetGraphResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *GetGraphResp) sizeField1() (n int) {
	if x.Graph == nil {
		return n
	}
	n += fastpb.SizeMessage(1, x.GetGraph())
	return n
}

func (x *ListGraphReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *ListGraphReq) sizeField1() (n int) {
	if x.PageNum == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetPageNum())
	return n
}

func (x *ListGraphReq) sizeField2() (n int) {
	if x.PageSize == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetPageSize())
	return n
}

func (x *ListGraphReq) sizeField3() (n int) {
	if x.GraphName == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetGraphName())
	return n
}

func (x *ListGraphReq) sizeField4() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(4, x.GetUserId())
	return n
}

func (x *ListGraphResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *ListGraphResp) sizeField1() (n int) {
	if x.GraphList == nil {
		return n
	}
	for i := range x.GetGraphList() {
		n += fastpb.SizeMessage(1, x.GetGraphList()[i])
	}
	return n
}

func (x *ListGraphResp) sizeField2() (n int) {
	if x.Total == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetTotal())
	return n
}

func (x *StartEditReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *StartEditReq) sizeField1() (n int) {
	if x.GraphId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetGraphId())
	return n
}

func (x *StartEditReq) sizeField2() (n int) {
	if x.Version == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetVersion())
	return n
}

func (x *StartEditResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *StartEditResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *StartEditResp) sizeField2() (n int) {
	if !x.TmpReady {
		return n
	}
	n += fastpb.SizeBool(2, x.GetTmpReady())
	return n
}

func (x *StartEditResp) sizeField3() (n int) {
	if x.BasedOnVersion == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetBasedOnVersion())
	return n
}

func (x *StartEditResp) sizeField4() (n int) {
	if x.Message == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetMessage())
	return n
}

func (x *SaveReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *SaveReq) sizeField1() (n int) {
	if x.GraphId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetGraphId())
	return n
}

func (x *SaveReq) sizeField2() (n int) {
	if x.FromVersion == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetFromVersion())
	return n
}

func (x *SaveReq) sizeField3() (n int) {
	if x.ToVersion == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetToVersion())
	return n
}

func (x *SaveReq) sizeField4() (n int) {
	if x.OperatorUserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(4, x.GetOperatorUserId())
	return n
}

func (x *SaveReq) sizeField5() (n int) {
	if x.Remark == "" {
		return n
	}
	n += fastpb.SizeString(5, x.GetRemark())
	return n
}

func (x *SaveResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *SaveResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *SaveResp) sizeField2() (n int) {
	if x.FromVersion == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetFromVersion())
	return n
}

func (x *SaveResp) sizeField3() (n int) {
	if x.ToVersion == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetToVersion())
	return n
}

func (x *SaveResp) sizeField4() (n int) {
	if x.Message == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetMessage())
	return n
}

func (x *ListGraphMessageReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *ListGraphMessageReq) sizeField1() (n int) {
	if x.GraphId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetGraphId())
	return n
}

func (x *ListGraphMessageReq) sizeField2() (n int) {
	if x.PageSize == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetPageSize())
	return n
}

func (x *ListGraphMessageReq) sizeField3() (n int) {
	if x.LastCreateTime == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetLastCreateTime())
	return n
}

func (x *ListGraphMessageResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *ListGraphMessageResp) sizeField1() (n int) {
	if x.MessageList == nil {
		return n
	}
	for i := range x.GetMessageList() {
		n += fastpb.SizeMessage(1, x.GetMessageList()[i])
	}
	return n
}

func (x *ListGraphMessageResp) sizeField2() (n int) {
	if x.Total == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetTotal())
	return n
}

func (x *ListGraphMessageResp) sizeField3() (n int) {
	if !x.HasMore {
		return n
	}
	n += fastpb.SizeBool(3, x.GetHasMore())
	return n
}

func (x *AddGraphMessageReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *AddGraphMessageReq) sizeField1() (n int) {
	if x.GraphId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetGraphId())
	return n
}

func (x *AddGraphMessageReq) sizeField2() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetUserId())
	return n
}

func (x *AddGraphMessageReq) sizeField3() (n int) {
	if x.Role == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetRole())
	return n
}

func (x *AddGraphMessageReq) sizeField4() (n int) {
	if x.Content == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetContent())
	return n
}

func (x *AddGraphMessageResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *AddGraphMessageResp) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *CreateVersionReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *CreateVersionReq) sizeField1() (n int) {
	if x.GraphId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetGraphId())
	return n
}

func (x *CreateVersionReq) sizeField2() (n int) {
	if x.VersionName == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetVersionName())
	return n
}

func (x *CreateVersionResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *CreateVersionResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *CreateVersionResp) sizeField2() (n int) {
	if x.Version == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetVersion())
	return n
}

func (x *DeleteVersionReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *DeleteVersionReq) sizeField1() (n int) {
	if x.GraphId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetGraphId())
	return n
}

func (x *DeleteVersionReq) sizeField2() (n int) {
	if x.Version == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetVersion())
	return n
}

func (x *DeleteVersionResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *DeleteVersionResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *RenameVersionReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *RenameVersionReq) sizeField1() (n int) {
	if x.GraphId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetGraphId())
	return n
}

func (x *RenameVersionReq) sizeField2() (n int) {
	if x.Version == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetVersion())
	return n
}

func (x *RenameVersionReq) sizeField3() (n int) {
	if x.VersionName == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetVersionName())
	return n
}

func (x *RenameVersionResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *RenameVersionResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *ListVersionReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *ListVersionReq) sizeField1() (n int) {
	if x.GraphId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetGraphId())
	return n
}

func (x *ListVersionResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *ListVersionResp) sizeField1() (n int) {
	if x.VersionList == nil {
		return n
	}
	for i := range x.GetVersionList() {
		n += fastpb.SizeMessage(1, x.GetVersionList()[i])
	}
	return n
}

var fieldIDToName_GraphInfo = map[int32]string{
	1: "Id",
	2: "GraphName",
	3: "Description",
	4: "Cover",
	5: "UserId",
	6: "CurrentVersion",
	7: "HasTmp",
	8: "CreateTime",
	9: "UpdateTime",
}

var fieldIDToName_GraphVersionInfo = map[int32]string{
	1: "Version",
	2: "VersionName",
	3: "IsCurrent",
	4: "CreateTime",
	5: "UpdateTime",
}

var fieldIDToName_GraphMessage = map[int32]string{
	1: "Id",
	2: "GraphId",
	3: "UserId",
	4: "Role",
	5: "Content",
	6: "CreateTime",
	7: "UpdateTime",
	8: "IsDelete",
}

var fieldIDToName_AddGraphReq = map[int32]string{
	1: "GraphName",
	2: "Description",
	3: "Cover",
	4: "UserId",
}

var fieldIDToName_AddGraphResp = map[int32]string{
	1: "Id",
}

var fieldIDToName_DeleteGraphReq = map[int32]string{
	1: "Id",
}

var fieldIDToName_DeleteGraphResp = map[int32]string{
	1: "Success",
}

var fieldIDToName_UpdateGraphReq = map[int32]string{
	1: "Id",
	2: "GraphName",
	3: "Description",
	4: "Cover",
}

var fieldIDToName_UpdateGraphResp = map[int32]string{
	1: "Success",
}

var fieldIDToName_GetGraphReq = map[int32]string{
	1: "Id",
}

var fieldIDToName_GetGraphResp = map[int32]string{
	1: "Graph",
}

var fieldIDToName_ListGraphReq = map[int32]string{
	1: "PageNum",
	2: "PageSize",
	3: "GraphName",
	4: "UserId",
}

var fieldIDToName_ListGraphResp = map[int32]string{
	1: "GraphList",
	2: "Total",
}

var fieldIDToName_StartEditReq = map[int32]string{
	1: "GraphId",
	2: "Version",
}

var fieldIDToName_StartEditResp = map[int32]string{
	1: "Success",
	2: "TmpReady",
	3: "BasedOnVersion",
	4: "Message",
}

var fieldIDToName_SaveReq = map[int32]string{
	1: "GraphId",
	2: "FromVersion",
	3: "ToVersion",
	4: "OperatorUserId",
	5: "Remark",
}

var fieldIDToName_SaveResp = map[int32]string{
	1: "Success",
	2: "FromVersion",
	3: "ToVersion",
	4: "Message",
}

var fieldIDToName_ListGraphMessageReq = map[int32]string{
	1: "GraphId",
	2: "PageSize",
	3: "LastCreateTime",
}

var fieldIDToName_ListGraphMessageResp = map[int32]string{
	1: "MessageList",
	2: "Total",
	3: "HasMore",
}

var fieldIDToName_AddGraphMessageReq = map[int32]string{
	1: "GraphId",
	2: "UserId",
	3: "Role",
	4: "Content",
}

var fieldIDToName_AddGraphMessageResp = map[int32]string{
	1: "Id",
}

var fieldIDToName_CreateVersionReq = map[int32]string{
	1: "GraphId",
	2: "VersionName",
}

var fieldIDToName_CreateVersionResp = map[int32]string{
	1: "Success",
	2: "Version",
}

var fieldIDToName_DeleteVersionReq = map[int32]string{
	1: "GraphId",
	2: "Version",
}

var fieldIDToName_DeleteVersionResp = map[int32]string{
	1: "Success",
}

var fieldIDToName_RenameVersionReq = map[int32]string{
	1: "GraphId",
	2: "Version",
	3: "VersionName",
}

var fieldIDToName_RenameVersionResp = map[int32]string{
	1: "Success",
}

var fieldIDToName_ListVersionReq = map[int32]string{
	1: "GraphId",
}

var fieldIDToName_ListVersionResp = map[int32]string{
	1: "VersionList",
}
