// Code generated by hertz generator.

package graph

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _graphMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addgraphMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chattomodifygraphMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletegraphMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _savegraphMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updategraphMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadgraphMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _editMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _discardworkinggraphMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _starteditMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkinggraphMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getgraphvobyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listgraphvobypageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _messageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listgraphmessageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _versionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _creategraphversionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletegraphversionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listgraphversionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _renamegraphversionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _suggestionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcurrentsuggestionMw() []app.HandlerFunc {
	// your code...
	return nil
}
