// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package document

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *ParsePersonalPDFReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ParsePersonalPDFReq[number], err)
}

func (x *ParsePersonalPDFReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ParsePersonalPDFReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.PdfId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ParsePersonalPDFReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.FileName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ParsePersonalPDFReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.DisplayName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ParseProjectPDFReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ParseProjectPDFReq[number], err)
}

func (x *ParseProjectPDFReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.ProjectId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ParseProjectPDFReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.PdfId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ParseProjectPDFReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.FileName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ParseProjectPDFReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.DisplayName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ParsePDFResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ParsePDFResp[number], err)
}

func (x *ParsePDFResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Success, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *ParsePDFResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.DocumentId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ParsePDFResp) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.ErrorMessage, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GetDocumentReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GetDocumentReq[number], err)
}

func (x *GetDocumentReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.DocumentId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListDocumentsReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListDocumentsReq[number], err)
}

func (x *ListDocumentsReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.OwnerType = OwnerType(v)
	return offset, nil
}

func (x *ListDocumentsReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.OwnerId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListDocumentsReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Page, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListDocumentsReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.PageSize, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *SearchDocumentsReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SearchDocumentsReq[number], err)
}

func (x *SearchDocumentsReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SearchDocumentsReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.ProjectId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SearchDocumentsReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Query, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SearchDocumentsReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.TopK, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *DocumentChunk) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DocumentChunk[number], err)
}

func (x *DocumentChunk) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.ChunkId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *DocumentChunk) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Text, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *DocumentChunk) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Page, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *DocumentChunk) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Order, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *Document) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 8:
		offset, err = x.fastReadField8(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 9:
		offset, err = x.fastReadField9(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 10:
		offset, err = x.fastReadField10(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 11:
		offset, err = x.fastReadField11(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_Document[number], err)
}

func (x *Document) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.DocumentId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Document) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.OwnerType = OwnerType(v)
	return offset, nil
}

func (x *Document) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.OwnerId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Document) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.PdfId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Document) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.FileName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Document) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.DisplayName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Document) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.ParseStatus = ParseStatus(v)
	return offset, nil
}

func (x *Document) fastReadField8(buf []byte, _type int8) (offset int, err error) {
	x.Summary, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Document) fastReadField9(buf []byte, _type int8) (offset int, err error) {
	var v DocumentChunk
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Chunks = append(x.Chunks, &v)
	return offset, nil
}

func (x *Document) fastReadField10(buf []byte, _type int8) (offset int, err error) {
	x.CreatedAt, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Document) fastReadField11(buf []byte, _type int8) (offset int, err error) {
	x.UpdatedAt, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GetDocumentResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GetDocumentResp[number], err)
}

func (x *GetDocumentResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v Document
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Document = &v
	return offset, nil
}

func (x *ListDocumentsResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListDocumentsResp[number], err)
}

func (x *ListDocumentsResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v Document
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Documents = append(x.Documents, &v)
	return offset, nil
}

func (x *ListDocumentsResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Total, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *SearchResult) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SearchResult[number], err)
}

func (x *SearchResult) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.DocumentId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SearchResult) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.DocumentName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SearchResult) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.ChunkId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SearchResult) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Text, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SearchResult) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.Score, offset, err = fastpb.ReadDouble(buf, _type)
	return offset, err
}

func (x *SearchDocumentsResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SearchDocumentsResp[number], err)
}

func (x *SearchDocumentsResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v SearchResult
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Results = append(x.Results, &v)
	return offset, nil
}

func (x *ParsePersonalPDFReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *ParsePersonalPDFReq) fastWriteField1(buf []byte) (offset int) {
	if x.UserId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetUserId())
	return offset
}

func (x *ParsePersonalPDFReq) fastWriteField2(buf []byte) (offset int) {
	if x.PdfId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetPdfId())
	return offset
}

func (x *ParsePersonalPDFReq) fastWriteField3(buf []byte) (offset int) {
	if x.FileName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetFileName())
	return offset
}

func (x *ParsePersonalPDFReq) fastWriteField4(buf []byte) (offset int) {
	if x.DisplayName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetDisplayName())
	return offset
}

func (x *ParseProjectPDFReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *ParseProjectPDFReq) fastWriteField1(buf []byte) (offset int) {
	if x.ProjectId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetProjectId())
	return offset
}

func (x *ParseProjectPDFReq) fastWriteField2(buf []byte) (offset int) {
	if x.PdfId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetPdfId())
	return offset
}

func (x *ParseProjectPDFReq) fastWriteField3(buf []byte) (offset int) {
	if x.FileName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetFileName())
	return offset
}

func (x *ParseProjectPDFReq) fastWriteField4(buf []byte) (offset int) {
	if x.DisplayName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetDisplayName())
	return offset
}

func (x *ParsePDFResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *ParsePDFResp) fastWriteField1(buf []byte) (offset int) {
	if !x.Success {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 1, x.GetSuccess())
	return offset
}

func (x *ParsePDFResp) fastWriteField2(buf []byte) (offset int) {
	if x.DocumentId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetDocumentId())
	return offset
}

func (x *ParsePDFResp) fastWriteField3(buf []byte) (offset int) {
	if x.ErrorMessage == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetErrorMessage())
	return offset
}

func (x *GetDocumentReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *GetDocumentReq) fastWriteField1(buf []byte) (offset int) {
	if x.DocumentId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetDocumentId())
	return offset
}

func (x *ListDocumentsReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *ListDocumentsReq) fastWriteField1(buf []byte) (offset int) {
	if x.OwnerType == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 1, int32(x.GetOwnerType()))
	return offset
}

func (x *ListDocumentsReq) fastWriteField2(buf []byte) (offset int) {
	if x.OwnerId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetOwnerId())
	return offset
}

func (x *ListDocumentsReq) fastWriteField3(buf []byte) (offset int) {
	if x.Page == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 3, x.GetPage())
	return offset
}

func (x *ListDocumentsReq) fastWriteField4(buf []byte) (offset int) {
	if x.PageSize == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 4, x.GetPageSize())
	return offset
}

func (x *SearchDocumentsReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *SearchDocumentsReq) fastWriteField1(buf []byte) (offset int) {
	if x.UserId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetUserId())
	return offset
}

func (x *SearchDocumentsReq) fastWriteField2(buf []byte) (offset int) {
	if x.ProjectId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetProjectId())
	return offset
}

func (x *SearchDocumentsReq) fastWriteField3(buf []byte) (offset int) {
	if x.Query == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetQuery())
	return offset
}

func (x *SearchDocumentsReq) fastWriteField4(buf []byte) (offset int) {
	if x.TopK == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 4, x.GetTopK())
	return offset
}

func (x *DocumentChunk) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *DocumentChunk) fastWriteField1(buf []byte) (offset int) {
	if x.ChunkId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetChunkId())
	return offset
}

func (x *DocumentChunk) fastWriteField2(buf []byte) (offset int) {
	if x.Text == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetText())
	return offset
}

func (x *DocumentChunk) fastWriteField3(buf []byte) (offset int) {
	if x.Page == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 3, x.GetPage())
	return offset
}

func (x *DocumentChunk) fastWriteField4(buf []byte) (offset int) {
	if x.Order == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 4, x.GetOrder())
	return offset
}

func (x *Document) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	offset += x.fastWriteField8(buf[offset:])
	offset += x.fastWriteField9(buf[offset:])
	offset += x.fastWriteField10(buf[offset:])
	offset += x.fastWriteField11(buf[offset:])
	return offset
}

func (x *Document) fastWriteField1(buf []byte) (offset int) {
	if x.DocumentId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetDocumentId())
	return offset
}

func (x *Document) fastWriteField2(buf []byte) (offset int) {
	if x.OwnerType == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 2, int32(x.GetOwnerType()))
	return offset
}

func (x *Document) fastWriteField3(buf []byte) (offset int) {
	if x.OwnerId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetOwnerId())
	return offset
}

func (x *Document) fastWriteField4(buf []byte) (offset int) {
	if x.PdfId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetPdfId())
	return offset
}

func (x *Document) fastWriteField5(buf []byte) (offset int) {
	if x.FileName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 5, x.GetFileName())
	return offset
}

func (x *Document) fastWriteField6(buf []byte) (offset int) {
	if x.DisplayName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 6, x.GetDisplayName())
	return offset
}

func (x *Document) fastWriteField7(buf []byte) (offset int) {
	if x.ParseStatus == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 7, int32(x.GetParseStatus()))
	return offset
}

func (x *Document) fastWriteField8(buf []byte) (offset int) {
	if x.Summary == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 8, x.GetSummary())
	return offset
}

func (x *Document) fastWriteField9(buf []byte) (offset int) {
	if x.Chunks == nil {
		return offset
	}
	for i := range x.GetChunks() {
		offset += fastpb.WriteMessage(buf[offset:], 9, x.GetChunks()[i])
	}
	return offset
}

func (x *Document) fastWriteField10(buf []byte) (offset int) {
	if x.CreatedAt == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 10, x.GetCreatedAt())
	return offset
}

func (x *Document) fastWriteField11(buf []byte) (offset int) {
	if x.UpdatedAt == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 11, x.GetUpdatedAt())
	return offset
}

func (x *GetDocumentResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *GetDocumentResp) fastWriteField1(buf []byte) (offset int) {
	if x.Document == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 1, x.GetDocument())
	return offset
}

func (x *ListDocumentsResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *ListDocumentsResp) fastWriteField1(buf []byte) (offset int) {
	if x.Documents == nil {
		return offset
	}
	for i := range x.GetDocuments() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetDocuments()[i])
	}
	return offset
}

func (x *ListDocumentsResp) fastWriteField2(buf []byte) (offset int) {
	if x.Total == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetTotal())
	return offset
}

func (x *SearchResult) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *SearchResult) fastWriteField1(buf []byte) (offset int) {
	if x.DocumentId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetDocumentId())
	return offset
}

func (x *SearchResult) fastWriteField2(buf []byte) (offset int) {
	if x.DocumentName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetDocumentName())
	return offset
}

func (x *SearchResult) fastWriteField3(buf []byte) (offset int) {
	if x.ChunkId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetChunkId())
	return offset
}

func (x *SearchResult) fastWriteField4(buf []byte) (offset int) {
	if x.Text == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetText())
	return offset
}

func (x *SearchResult) fastWriteField5(buf []byte) (offset int) {
	if x.Score == 0 {
		return offset
	}
	offset += fastpb.WriteDouble(buf[offset:], 5, x.GetScore())
	return offset
}

func (x *SearchDocumentsResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *SearchDocumentsResp) fastWriteField1(buf []byte) (offset int) {
	if x.Results == nil {
		return offset
	}
	for i := range x.GetResults() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetResults()[i])
	}
	return offset
}

func (x *ParsePersonalPDFReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *ParsePersonalPDFReq) sizeField1() (n int) {
	if x.UserId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetUserId())
	return n
}

func (x *ParsePersonalPDFReq) sizeField2() (n int) {
	if x.PdfId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetPdfId())
	return n
}

func (x *ParsePersonalPDFReq) sizeField3() (n int) {
	if x.FileName == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetFileName())
	return n
}

func (x *ParsePersonalPDFReq) sizeField4() (n int) {
	if x.DisplayName == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetDisplayName())
	return n
}

func (x *ParseProjectPDFReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *ParseProjectPDFReq) sizeField1() (n int) {
	if x.ProjectId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetProjectId())
	return n
}

func (x *ParseProjectPDFReq) sizeField2() (n int) {
	if x.PdfId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetPdfId())
	return n
}

func (x *ParseProjectPDFReq) sizeField3() (n int) {
	if x.FileName == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetFileName())
	return n
}

func (x *ParseProjectPDFReq) sizeField4() (n int) {
	if x.DisplayName == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetDisplayName())
	return n
}

func (x *ParsePDFResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *ParsePDFResp) sizeField1() (n int) {
	if !x.Success {
		return n
	}
	n += fastpb.SizeBool(1, x.GetSuccess())
	return n
}

func (x *ParsePDFResp) sizeField2() (n int) {
	if x.DocumentId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetDocumentId())
	return n
}

func (x *ParsePDFResp) sizeField3() (n int) {
	if x.ErrorMessage == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetErrorMessage())
	return n
}

func (x *GetDocumentReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *GetDocumentReq) sizeField1() (n int) {
	if x.DocumentId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetDocumentId())
	return n
}

func (x *ListDocumentsReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *ListDocumentsReq) sizeField1() (n int) {
	if x.OwnerType == 0 {
		return n
	}
	n += fastpb.SizeInt32(1, int32(x.GetOwnerType()))
	return n
}

func (x *ListDocumentsReq) sizeField2() (n int) {
	if x.OwnerId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetOwnerId())
	return n
}

func (x *ListDocumentsReq) sizeField3() (n int) {
	if x.Page == 0 {
		return n
	}
	n += fastpb.SizeInt64(3, x.GetPage())
	return n
}

func (x *ListDocumentsReq) sizeField4() (n int) {
	if x.PageSize == 0 {
		return n
	}
	n += fastpb.SizeInt64(4, x.GetPageSize())
	return n
}

func (x *SearchDocumentsReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *SearchDocumentsReq) sizeField1() (n int) {
	if x.UserId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetUserId())
	return n
}

func (x *SearchDocumentsReq) sizeField2() (n int) {
	if x.ProjectId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetProjectId())
	return n
}

func (x *SearchDocumentsReq) sizeField3() (n int) {
	if x.Query == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetQuery())
	return n
}

func (x *SearchDocumentsReq) sizeField4() (n int) {
	if x.TopK == 0 {
		return n
	}
	n += fastpb.SizeInt64(4, x.GetTopK())
	return n
}

func (x *DocumentChunk) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *DocumentChunk) sizeField1() (n int) {
	if x.ChunkId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetChunkId())
	return n
}

func (x *DocumentChunk) sizeField2() (n int) {
	if x.Text == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetText())
	return n
}

func (x *DocumentChunk) sizeField3() (n int) {
	if x.Page == 0 {
		return n
	}
	n += fastpb.SizeInt64(3, x.GetPage())
	return n
}

func (x *DocumentChunk) sizeField4() (n int) {
	if x.Order == 0 {
		return n
	}
	n += fastpb.SizeInt64(4, x.GetOrder())
	return n
}

func (x *Document) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	n += x.sizeField6()
	n += x.sizeField7()
	n += x.sizeField8()
	n += x.sizeField9()
	n += x.sizeField10()
	n += x.sizeField11()
	return n
}

func (x *Document) sizeField1() (n int) {
	if x.DocumentId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetDocumentId())
	return n
}

func (x *Document) sizeField2() (n int) {
	if x.OwnerType == 0 {
		return n
	}
	n += fastpb.SizeInt32(2, int32(x.GetOwnerType()))
	return n
}

func (x *Document) sizeField3() (n int) {
	if x.OwnerId == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetOwnerId())
	return n
}

func (x *Document) sizeField4() (n int) {
	if x.PdfId == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetPdfId())
	return n
}

func (x *Document) sizeField5() (n int) {
	if x.FileName == "" {
		return n
	}
	n += fastpb.SizeString(5, x.GetFileName())
	return n
}

func (x *Document) sizeField6() (n int) {
	if x.DisplayName == "" {
		return n
	}
	n += fastpb.SizeString(6, x.GetDisplayName())
	return n
}

func (x *Document) sizeField7() (n int) {
	if x.ParseStatus == 0 {
		return n
	}
	n += fastpb.SizeInt32(7, int32(x.GetParseStatus()))
	return n
}

func (x *Document) sizeField8() (n int) {
	if x.Summary == "" {
		return n
	}
	n += fastpb.SizeString(8, x.GetSummary())
	return n
}

func (x *Document) sizeField9() (n int) {
	if x.Chunks == nil {
		return n
	}
	for i := range x.GetChunks() {
		n += fastpb.SizeMessage(9, x.GetChunks()[i])
	}
	return n
}

func (x *Document) sizeField10() (n int) {
	if x.CreatedAt == "" {
		return n
	}
	n += fastpb.SizeString(10, x.GetCreatedAt())
	return n
}

func (x *Document) sizeField11() (n int) {
	if x.UpdatedAt == "" {
		return n
	}
	n += fastpb.SizeString(11, x.GetUpdatedAt())
	return n
}

func (x *GetDocumentResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *GetDocumentResp) sizeField1() (n int) {
	if x.Document == nil {
		return n
	}
	n += fastpb.SizeMessage(1, x.GetDocument())
	return n
}

func (x *ListDocumentsResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *ListDocumentsResp) sizeField1() (n int) {
	if x.Documents == nil {
		return n
	}
	for i := range x.GetDocuments() {
		n += fastpb.SizeMessage(1, x.GetDocuments()[i])
	}
	return n
}

func (x *ListDocumentsResp) sizeField2() (n int) {
	if x.Total == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetTotal())
	return n
}

func (x *SearchResult) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *SearchResult) sizeField1() (n int) {
	if x.DocumentId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetDocumentId())
	return n
}

func (x *SearchResult) sizeField2() (n int) {
	if x.DocumentName == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetDocumentName())
	return n
}

func (x *SearchResult) sizeField3() (n int) {
	if x.ChunkId == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetChunkId())
	return n
}

func (x *SearchResult) sizeField4() (n int) {
	if x.Text == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetText())
	return n
}

func (x *SearchResult) sizeField5() (n int) {
	if x.Score == 0 {
		return n
	}
	n += fastpb.SizeDouble(5, x.GetScore())
	return n
}

func (x *SearchDocumentsResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *SearchDocumentsResp) sizeField1() (n int) {
	if x.Results == nil {
		return n
	}
	for i := range x.GetResults() {
		n += fastpb.SizeMessage(1, x.GetResults()[i])
	}
	return n
}

var fieldIDToName_ParsePersonalPDFReq = map[int32]string{
	1: "UserId",
	2: "PdfId",
	3: "FileName",
	4: "DisplayName",
}

var fieldIDToName_ParseProjectPDFReq = map[int32]string{
	1: "ProjectId",
	2: "PdfId",
	3: "FileName",
	4: "DisplayName",
}

var fieldIDToName_ParsePDFResp = map[int32]string{
	1: "Success",
	2: "DocumentId",
	3: "ErrorMessage",
}

var fieldIDToName_GetDocumentReq = map[int32]string{
	1: "DocumentId",
}

var fieldIDToName_ListDocumentsReq = map[int32]string{
	1: "OwnerType",
	2: "OwnerId",
	3: "Page",
	4: "PageSize",
}

var fieldIDToName_SearchDocumentsReq = map[int32]string{
	1: "UserId",
	2: "ProjectId",
	3: "Query",
	4: "TopK",
}

var fieldIDToName_DocumentChunk = map[int32]string{
	1: "ChunkId",
	2: "Text",
	3: "Page",
	4: "Order",
}

var fieldIDToName_Document = map[int32]string{
	1:  "DocumentId",
	2:  "OwnerType",
	3:  "OwnerId",
	4:  "PdfId",
	5:  "FileName",
	6:  "DisplayName",
	7:  "ParseStatus",
	8:  "Summary",
	9:  "Chunks",
	10: "CreatedAt",
	11: "UpdatedAt",
}

var fieldIDToName_GetDocumentResp = map[int32]string{
	1: "Document",
}

var fieldIDToName_ListDocumentsResp = map[int32]string{
	1: "Documents",
	2: "Total",
}

var fieldIDToName_SearchResult = map[int32]string{
	1: "DocumentId",
	2: "DocumentName",
	3: "ChunkId",
	4: "Text",
	5: "Score",
}

var fieldIDToName_SearchDocumentsResp = map[int32]string{
	1: "Results",
}
