// Code generated by hertz generator.

package document

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _documentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadprojectdocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploaduserdocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}
