// Code generated by Kitex v0.9.1. DO NOT EDIT.

package graphservice

import (
	"context"
	graph "github.com/MoScenix/industrial-fault-tree-ai/rpc_gen/kitex_gen/graph"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddGraph(ctx context.Context, Req *graph.AddGraphReq, callOptions ...callopt.Option) (r *graph.AddGraphResp, err error)
	DeleteGraph(ctx context.Context, Req *graph.DeleteGraphReq, callOptions ...callopt.Option) (r *graph.DeleteGraphResp, err error)
	UpdateGraph(ctx context.Context, Req *graph.UpdateGraphReq, callOptions ...callopt.Option) (r *graph.UpdateGraphResp, err error)
	GetGraph(ctx context.Context, Req *graph.GetGraphReq, callOptions ...callopt.Option) (r *graph.GetGraphResp, err error)
	ListGraph(ctx context.Context, Req *graph.ListGraphReq, callOptions ...callopt.Option) (r *graph.ListGraphResp, err error)
	StartEdit(ctx context.Context, Req *graph.StartEditReq, callOptions ...callopt.Option) (r *graph.StartEditResp, err error)
	Save(ctx context.Context, Req *graph.SaveReq, callOptions ...callopt.Option) (r *graph.SaveResp, err error)
	AddGraphMessage(ctx context.Context, Req *graph.AddGraphMessageReq, callOptions ...callopt.Option) (r *graph.AddGraphMessageResp, err error)
	ListGraphMessage(ctx context.Context, Req *graph.ListGraphMessageReq, callOptions ...callopt.Option) (r *graph.ListGraphMessageResp, err error)
	CreateVersion(ctx context.Context, Req *graph.CreateVersionReq, callOptions ...callopt.Option) (r *graph.CreateVersionResp, err error)
	DeleteVersion(ctx context.Context, Req *graph.DeleteVersionReq, callOptions ...callopt.Option) (r *graph.DeleteVersionResp, err error)
	RenameVersion(ctx context.Context, Req *graph.RenameVersionReq, callOptions ...callopt.Option) (r *graph.RenameVersionResp, err error)
	ListVersion(ctx context.Context, Req *graph.ListVersionReq, callOptions ...callopt.Option) (r *graph.ListVersionResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kGraphServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kGraphServiceClient struct {
	*kClient
}

func (p *kGraphServiceClient) AddGraph(ctx context.Context, Req *graph.AddGraphReq, callOptions ...callopt.Option) (r *graph.AddGraphResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddGraph(ctx, Req)
}

func (p *kGraphServiceClient) DeleteGraph(ctx context.Context, Req *graph.DeleteGraphReq, callOptions ...callopt.Option) (r *graph.DeleteGraphResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteGraph(ctx, Req)
}

func (p *kGraphServiceClient) UpdateGraph(ctx context.Context, Req *graph.UpdateGraphReq, callOptions ...callopt.Option) (r *graph.UpdateGraphResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateGraph(ctx, Req)
}

func (p *kGraphServiceClient) GetGraph(ctx context.Context, Req *graph.GetGraphReq, callOptions ...callopt.Option) (r *graph.GetGraphResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetGraph(ctx, Req)
}

func (p *kGraphServiceClient) ListGraph(ctx context.Context, Req *graph.ListGraphReq, callOptions ...callopt.Option) (r *graph.ListGraphResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListGraph(ctx, Req)
}

func (p *kGraphServiceClient) StartEdit(ctx context.Context, Req *graph.StartEditReq, callOptions ...callopt.Option) (r *graph.StartEditResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartEdit(ctx, Req)
}

func (p *kGraphServiceClient) Save(ctx context.Context, Req *graph.SaveReq, callOptions ...callopt.Option) (r *graph.SaveResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Save(ctx, Req)
}

func (p *kGraphServiceClient) AddGraphMessage(ctx context.Context, Req *graph.AddGraphMessageReq, callOptions ...callopt.Option) (r *graph.AddGraphMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddGraphMessage(ctx, Req)
}

func (p *kGraphServiceClient) ListGraphMessage(ctx context.Context, Req *graph.ListGraphMessageReq, callOptions ...callopt.Option) (r *graph.ListGraphMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListGraphMessage(ctx, Req)
}

func (p *kGraphServiceClient) CreateVersion(ctx context.Context, Req *graph.CreateVersionReq, callOptions ...callopt.Option) (r *graph.CreateVersionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateVersion(ctx, Req)
}

func (p *kGraphServiceClient) DeleteVersion(ctx context.Context, Req *graph.DeleteVersionReq, callOptions ...callopt.Option) (r *graph.DeleteVersionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteVersion(ctx, Req)
}

func (p *kGraphServiceClient) RenameVersion(ctx context.Context, Req *graph.RenameVersionReq, callOptions ...callopt.Option) (r *graph.RenameVersionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RenameVersion(ctx, Req)
}

func (p *kGraphServiceClient) ListVersion(ctx context.Context, Req *graph.ListVersionReq, callOptions ...callopt.Option) (r *graph.ListVersionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListVersion(ctx, Req)
}
