// Code generated by Kitex v0.9.1. DO NOT EDIT.

package graphservice

import (
	"context"
	"errors"
	graph "github.com/MoScenix/industrial-fault-tree-ai/rpc_gen/kitex_gen/graph"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AddGraph": kitex.NewMethodInfo(
		addGraphHandler,
		newAddGraphArgs,
		newAddGraphResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteGraph": kitex.NewMethodInfo(
		deleteGraphHandler,
		newDeleteGraphArgs,
		newDeleteGraphResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateGraph": kitex.NewMethodInfo(
		updateGraphHandler,
		newUpdateGraphArgs,
		newUpdateGraphResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetGraph": kitex.NewMethodInfo(
		getGraphHandler,
		newGetGraphArgs,
		newGetGraphResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListGraph": kitex.NewMethodInfo(
		listGraphHandler,
		newListGraphArgs,
		newListGraphResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"StartEdit": kitex.NewMethodInfo(
		startEditHandler,
		newStartEditArgs,
		newStartEditResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Save": kitex.NewMethodInfo(
		saveHandler,
		newSaveArgs,
		newSaveResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AddGraphMessage": kitex.NewMethodInfo(
		addGraphMessageHandler,
		newAddGraphMessageArgs,
		newAddGraphMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListGraphMessage": kitex.NewMethodInfo(
		listGraphMessageHandler,
		newListGraphMessageArgs,
		newListGraphMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateVersion": kitex.NewMethodInfo(
		createVersionHandler,
		newCreateVersionArgs,
		newCreateVersionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteVersion": kitex.NewMethodInfo(
		deleteVersionHandler,
		newDeleteVersionArgs,
		newDeleteVersionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RenameVersion": kitex.NewMethodInfo(
		renameVersionHandler,
		newRenameVersionArgs,
		newRenameVersionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListVersion": kitex.NewMethodInfo(
		listVersionHandler,
		newListVersionArgs,
		newListVersionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	graphServiceServiceInfo                = NewServiceInfo()
	graphServiceServiceInfoForClient       = NewServiceInfoForClient()
	graphServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return graphServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return graphServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return graphServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "GraphService"
	handlerType := (*graph.GraphService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "graph",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func addGraphHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(graph.AddGraphReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(graph.GraphService).AddGraph(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddGraphArgs:
		success, err := handler.(graph.GraphService).AddGraph(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddGraphResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddGraphArgs() interface{} {
	return &AddGraphArgs{}
}

func newAddGraphResult() interface{} {
	return &AddGraphResult{}
}

type AddGraphArgs struct {
	Req *graph.AddGraphReq
}

func (p *AddGraphArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(graph.AddGraphReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AddGraphArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AddGraphArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AddGraphArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddGraphArgs) Unmarshal(in []byte) error {
	msg := new(graph.AddGraphReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddGraphArgs_Req_DEFAULT *graph.AddGraphReq

func (p *AddGraphArgs) GetReq() *graph.AddGraphReq {
	if !p.IsSetReq() {
		return AddGraphArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddGraphArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddGraphArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddGraphResult struct {
	Success *graph.AddGraphResp
}

var AddGraphResult_Success_DEFAULT *graph.AddGraphResp

func (p *AddGraphResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(graph.AddGraphResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AddGraphResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AddGraphResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AddGraphResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddGraphResult) Unmarshal(in []byte) error {
	msg := new(graph.AddGraphResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddGraphResult) GetSuccess() *graph.AddGraphResp {
	if !p.IsSetSuccess() {
		return AddGraphResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddGraphResult) SetSuccess(x interface{}) {
	p.Success = x.(*graph.AddGraphResp)
}

func (p *AddGraphResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddGraphResult) GetResult() interface{} {
	return p.Success
}

func deleteGraphHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(graph.DeleteGraphReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(graph.GraphService).DeleteGraph(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteGraphArgs:
		success, err := handler.(graph.GraphService).DeleteGraph(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteGraphResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteGraphArgs() interface{} {
	return &DeleteGraphArgs{}
}

func newDeleteGraphResult() interface{} {
	return &DeleteGraphResult{}
}

type DeleteGraphArgs struct {
	Req *graph.DeleteGraphReq
}

func (p *DeleteGraphArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(graph.DeleteGraphReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DeleteGraphArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DeleteGraphArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DeleteGraphArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteGraphArgs) Unmarshal(in []byte) error {
	msg := new(graph.DeleteGraphReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteGraphArgs_Req_DEFAULT *graph.DeleteGraphReq

func (p *DeleteGraphArgs) GetReq() *graph.DeleteGraphReq {
	if !p.IsSetReq() {
		return DeleteGraphArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteGraphArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteGraphArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteGraphResult struct {
	Success *graph.DeleteGraphResp
}

var DeleteGraphResult_Success_DEFAULT *graph.DeleteGraphResp

func (p *DeleteGraphResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(graph.DeleteGraphResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DeleteGraphResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DeleteGraphResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DeleteGraphResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteGraphResult) Unmarshal(in []byte) error {
	msg := new(graph.DeleteGraphResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteGraphResult) GetSuccess() *graph.DeleteGraphResp {
	if !p.IsSetSuccess() {
		return DeleteGraphResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteGraphResult) SetSuccess(x interface{}) {
	p.Success = x.(*graph.DeleteGraphResp)
}

func (p *DeleteGraphResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteGraphResult) GetResult() interface{} {
	return p.Success
}

func updateGraphHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(graph.UpdateGraphReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(graph.GraphService).UpdateGraph(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateGraphArgs:
		success, err := handler.(graph.GraphService).UpdateGraph(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateGraphResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateGraphArgs() interface{} {
	return &UpdateGraphArgs{}
}

func newUpdateGraphResult() interface{} {
	return &UpdateGraphResult{}
}

type UpdateGraphArgs struct {
	Req *graph.UpdateGraphReq
}

func (p *UpdateGraphArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(graph.UpdateGraphReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UpdateGraphArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UpdateGraphArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UpdateGraphArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateGraphArgs) Unmarshal(in []byte) error {
	msg := new(graph.UpdateGraphReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateGraphArgs_Req_DEFAULT *graph.UpdateGraphReq

func (p *UpdateGraphArgs) GetReq() *graph.UpdateGraphReq {
	if !p.IsSetReq() {
		return UpdateGraphArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateGraphArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateGraphArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateGraphResult struct {
	Success *graph.UpdateGraphResp
}

var UpdateGraphResult_Success_DEFAULT *graph.UpdateGraphResp

func (p *UpdateGraphResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(graph.UpdateGraphResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UpdateGraphResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UpdateGraphResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UpdateGraphResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateGraphResult) Unmarshal(in []byte) error {
	msg := new(graph.UpdateGraphResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateGraphResult) GetSuccess() *graph.UpdateGraphResp {
	if !p.IsSetSuccess() {
		return UpdateGraphResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateGraphResult) SetSuccess(x interface{}) {
	p.Success = x.(*graph.UpdateGraphResp)
}

func (p *UpdateGraphResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateGraphResult) GetResult() interface{} {
	return p.Success
}

func getGraphHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(graph.GetGraphReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(graph.GraphService).GetGraph(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetGraphArgs:
		success, err := handler.(graph.GraphService).GetGraph(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetGraphResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetGraphArgs() interface{} {
	return &GetGraphArgs{}
}

func newGetGraphResult() interface{} {
	return &GetGraphResult{}
}

type GetGraphArgs struct {
	Req *graph.GetGraphReq
}

func (p *GetGraphArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(graph.GetGraphReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetGraphArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetGraphArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetGraphArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetGraphArgs) Unmarshal(in []byte) error {
	msg := new(graph.GetGraphReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetGraphArgs_Req_DEFAULT *graph.GetGraphReq

func (p *GetGraphArgs) GetReq() *graph.GetGraphReq {
	if !p.IsSetReq() {
		return GetGraphArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetGraphArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetGraphArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetGraphResult struct {
	Success *graph.GetGraphResp
}

var GetGraphResult_Success_DEFAULT *graph.GetGraphResp

func (p *GetGraphResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(graph.GetGraphResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetGraphResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetGraphResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetGraphResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetGraphResult) Unmarshal(in []byte) error {
	msg := new(graph.GetGraphResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetGraphResult) GetSuccess() *graph.GetGraphResp {
	if !p.IsSetSuccess() {
		return GetGraphResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetGraphResult) SetSuccess(x interface{}) {
	p.Success = x.(*graph.GetGraphResp)
}

func (p *GetGraphResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetGraphResult) GetResult() interface{} {
	return p.Success
}

func listGraphHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(graph.ListGraphReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(graph.GraphService).ListGraph(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListGraphArgs:
		success, err := handler.(graph.GraphService).ListGraph(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListGraphResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListGraphArgs() interface{} {
	return &ListGraphArgs{}
}

func newListGraphResult() interface{} {
	return &ListGraphResult{}
}

type ListGraphArgs struct {
	Req *graph.ListGraphReq
}

func (p *ListGraphArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(graph.ListGraphReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListGraphArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListGraphArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListGraphArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListGraphArgs) Unmarshal(in []byte) error {
	msg := new(graph.ListGraphReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListGraphArgs_Req_DEFAULT *graph.ListGraphReq

func (p *ListGraphArgs) GetReq() *graph.ListGraphReq {
	if !p.IsSetReq() {
		return ListGraphArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListGraphArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListGraphArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListGraphResult struct {
	Success *graph.ListGraphResp
}

var ListGraphResult_Success_DEFAULT *graph.ListGraphResp

func (p *ListGraphResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(graph.ListGraphResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListGraphResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListGraphResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListGraphResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListGraphResult) Unmarshal(in []byte) error {
	msg := new(graph.ListGraphResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListGraphResult) GetSuccess() *graph.ListGraphResp {
	if !p.IsSetSuccess() {
		return ListGraphResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListGraphResult) SetSuccess(x interface{}) {
	p.Success = x.(*graph.ListGraphResp)
}

func (p *ListGraphResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListGraphResult) GetResult() interface{} {
	return p.Success
}

func startEditHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(graph.StartEditReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(graph.GraphService).StartEdit(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *StartEditArgs:
		success, err := handler.(graph.GraphService).StartEdit(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*StartEditResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newStartEditArgs() interface{} {
	return &StartEditArgs{}
}

func newStartEditResult() interface{} {
	return &StartEditResult{}
}

type StartEditArgs struct {
	Req *graph.StartEditReq
}

func (p *StartEditArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(graph.StartEditReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *StartEditArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *StartEditArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *StartEditArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *StartEditArgs) Unmarshal(in []byte) error {
	msg := new(graph.StartEditReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var StartEditArgs_Req_DEFAULT *graph.StartEditReq

func (p *StartEditArgs) GetReq() *graph.StartEditReq {
	if !p.IsSetReq() {
		return StartEditArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *StartEditArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StartEditArgs) GetFirstArgument() interface{} {
	return p.Req
}

type StartEditResult struct {
	Success *graph.StartEditResp
}

var StartEditResult_Success_DEFAULT *graph.StartEditResp

func (p *StartEditResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(graph.StartEditResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *StartEditResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *StartEditResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *StartEditResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *StartEditResult) Unmarshal(in []byte) error {
	msg := new(graph.StartEditResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *StartEditResult) GetSuccess() *graph.StartEditResp {
	if !p.IsSetSuccess() {
		return StartEditResult_Success_DEFAULT
	}
	return p.Success
}

func (p *StartEditResult) SetSuccess(x interface{}) {
	p.Success = x.(*graph.StartEditResp)
}

func (p *StartEditResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StartEditResult) GetResult() interface{} {
	return p.Success
}

func saveHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(graph.SaveReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(graph.GraphService).Save(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SaveArgs:
		success, err := handler.(graph.GraphService).Save(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SaveResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSaveArgs() interface{} {
	return &SaveArgs{}
}

func newSaveResult() interface{} {
	return &SaveResult{}
}

type SaveArgs struct {
	Req *graph.SaveReq
}

func (p *SaveArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(graph.SaveReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SaveArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SaveArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SaveArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SaveArgs) Unmarshal(in []byte) error {
	msg := new(graph.SaveReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SaveArgs_Req_DEFAULT *graph.SaveReq

func (p *SaveArgs) GetReq() *graph.SaveReq {
	if !p.IsSetReq() {
		return SaveArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SaveArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SaveArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SaveResult struct {
	Success *graph.SaveResp
}

var SaveResult_Success_DEFAULT *graph.SaveResp

func (p *SaveResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(graph.SaveResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SaveResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SaveResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SaveResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SaveResult) Unmarshal(in []byte) error {
	msg := new(graph.SaveResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SaveResult) GetSuccess() *graph.SaveResp {
	if !p.IsSetSuccess() {
		return SaveResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SaveResult) SetSuccess(x interface{}) {
	p.Success = x.(*graph.SaveResp)
}

func (p *SaveResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SaveResult) GetResult() interface{} {
	return p.Success
}

func addGraphMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(graph.AddGraphMessageReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(graph.GraphService).AddGraphMessage(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddGraphMessageArgs:
		success, err := handler.(graph.GraphService).AddGraphMessage(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddGraphMessageResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddGraphMessageArgs() interface{} {
	return &AddGraphMessageArgs{}
}

func newAddGraphMessageResult() interface{} {
	return &AddGraphMessageResult{}
}

type AddGraphMessageArgs struct {
	Req *graph.AddGraphMessageReq
}

func (p *AddGraphMessageArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(graph.AddGraphMessageReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AddGraphMessageArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AddGraphMessageArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AddGraphMessageArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddGraphMessageArgs) Unmarshal(in []byte) error {
	msg := new(graph.AddGraphMessageReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddGraphMessageArgs_Req_DEFAULT *graph.AddGraphMessageReq

func (p *AddGraphMessageArgs) GetReq() *graph.AddGraphMessageReq {
	if !p.IsSetReq() {
		return AddGraphMessageArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddGraphMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddGraphMessageArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddGraphMessageResult struct {
	Success *graph.AddGraphMessageResp
}

var AddGraphMessageResult_Success_DEFAULT *graph.AddGraphMessageResp

func (p *AddGraphMessageResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(graph.AddGraphMessageResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AddGraphMessageResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AddGraphMessageResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AddGraphMessageResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddGraphMessageResult) Unmarshal(in []byte) error {
	msg := new(graph.AddGraphMessageResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddGraphMessageResult) GetSuccess() *graph.AddGraphMessageResp {
	if !p.IsSetSuccess() {
		return AddGraphMessageResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddGraphMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*graph.AddGraphMessageResp)
}

func (p *AddGraphMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddGraphMessageResult) GetResult() interface{} {
	return p.Success
}

func listGraphMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(graph.ListGraphMessageReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(graph.GraphService).ListGraphMessage(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListGraphMessageArgs:
		success, err := handler.(graph.GraphService).ListGraphMessage(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListGraphMessageResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListGraphMessageArgs() interface{} {
	return &ListGraphMessageArgs{}
}

func newListGraphMessageResult() interface{} {
	return &ListGraphMessageResult{}
}

type ListGraphMessageArgs struct {
	Req *graph.ListGraphMessageReq
}

func (p *ListGraphMessageArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(graph.ListGraphMessageReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListGraphMessageArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListGraphMessageArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListGraphMessageArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListGraphMessageArgs) Unmarshal(in []byte) error {
	msg := new(graph.ListGraphMessageReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListGraphMessageArgs_Req_DEFAULT *graph.ListGraphMessageReq

func (p *ListGraphMessageArgs) GetReq() *graph.ListGraphMessageReq {
	if !p.IsSetReq() {
		return ListGraphMessageArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListGraphMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListGraphMessageArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListGraphMessageResult struct {
	Success *graph.ListGraphMessageResp
}

var ListGraphMessageResult_Success_DEFAULT *graph.ListGraphMessageResp

func (p *ListGraphMessageResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(graph.ListGraphMessageResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListGraphMessageResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListGraphMessageResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListGraphMessageResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListGraphMessageResult) Unmarshal(in []byte) error {
	msg := new(graph.ListGraphMessageResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListGraphMessageResult) GetSuccess() *graph.ListGraphMessageResp {
	if !p.IsSetSuccess() {
		return ListGraphMessageResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListGraphMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*graph.ListGraphMessageResp)
}

func (p *ListGraphMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListGraphMessageResult) GetResult() interface{} {
	return p.Success
}

func createVersionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(graph.CreateVersionReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(graph.GraphService).CreateVersion(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateVersionArgs:
		success, err := handler.(graph.GraphService).CreateVersion(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateVersionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateVersionArgs() interface{} {
	return &CreateVersionArgs{}
}

func newCreateVersionResult() interface{} {
	return &CreateVersionResult{}
}

type CreateVersionArgs struct {
	Req *graph.CreateVersionReq
}

func (p *CreateVersionArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(graph.CreateVersionReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *CreateVersionArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *CreateVersionArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *CreateVersionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateVersionArgs) Unmarshal(in []byte) error {
	msg := new(graph.CreateVersionReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateVersionArgs_Req_DEFAULT *graph.CreateVersionReq

func (p *CreateVersionArgs) GetReq() *graph.CreateVersionReq {
	if !p.IsSetReq() {
		return CreateVersionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateVersionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateVersionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateVersionResult struct {
	Success *graph.CreateVersionResp
}

var CreateVersionResult_Success_DEFAULT *graph.CreateVersionResp

func (p *CreateVersionResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(graph.CreateVersionResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *CreateVersionResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *CreateVersionResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *CreateVersionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateVersionResult) Unmarshal(in []byte) error {
	msg := new(graph.CreateVersionResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateVersionResult) GetSuccess() *graph.CreateVersionResp {
	if !p.IsSetSuccess() {
		return CreateVersionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateVersionResult) SetSuccess(x interface{}) {
	p.Success = x.(*graph.CreateVersionResp)
}

func (p *CreateVersionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateVersionResult) GetResult() interface{} {
	return p.Success
}

func deleteVersionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(graph.DeleteVersionReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(graph.GraphService).DeleteVersion(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteVersionArgs:
		success, err := handler.(graph.GraphService).DeleteVersion(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteVersionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteVersionArgs() interface{} {
	return &DeleteVersionArgs{}
}

func newDeleteVersionResult() interface{} {
	return &DeleteVersionResult{}
}

type DeleteVersionArgs struct {
	Req *graph.DeleteVersionReq
}

func (p *DeleteVersionArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(graph.DeleteVersionReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DeleteVersionArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DeleteVersionArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DeleteVersionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteVersionArgs) Unmarshal(in []byte) error {
	msg := new(graph.DeleteVersionReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteVersionArgs_Req_DEFAULT *graph.DeleteVersionReq

func (p *DeleteVersionArgs) GetReq() *graph.DeleteVersionReq {
	if !p.IsSetReq() {
		return DeleteVersionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteVersionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteVersionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteVersionResult struct {
	Success *graph.DeleteVersionResp
}

var DeleteVersionResult_Success_DEFAULT *graph.DeleteVersionResp

func (p *DeleteVersionResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(graph.DeleteVersionResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DeleteVersionResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DeleteVersionResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DeleteVersionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteVersionResult) Unmarshal(in []byte) error {
	msg := new(graph.DeleteVersionResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteVersionResult) GetSuccess() *graph.DeleteVersionResp {
	if !p.IsSetSuccess() {
		return DeleteVersionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteVersionResult) SetSuccess(x interface{}) {
	p.Success = x.(*graph.DeleteVersionResp)
}

func (p *DeleteVersionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteVersionResult) GetResult() interface{} {
	return p.Success
}

func renameVersionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(graph.RenameVersionReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(graph.GraphService).RenameVersion(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RenameVersionArgs:
		success, err := handler.(graph.GraphService).RenameVersion(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RenameVersionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRenameVersionArgs() interface{} {
	return &RenameVersionArgs{}
}

func newRenameVersionResult() interface{} {
	return &RenameVersionResult{}
}

type RenameVersionArgs struct {
	Req *graph.RenameVersionReq
}

func (p *RenameVersionArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(graph.RenameVersionReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *RenameVersionArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *RenameVersionArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *RenameVersionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RenameVersionArgs) Unmarshal(in []byte) error {
	msg := new(graph.RenameVersionReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RenameVersionArgs_Req_DEFAULT *graph.RenameVersionReq

func (p *RenameVersionArgs) GetReq() *graph.RenameVersionReq {
	if !p.IsSetReq() {
		return RenameVersionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RenameVersionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RenameVersionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RenameVersionResult struct {
	Success *graph.RenameVersionResp
}

var RenameVersionResult_Success_DEFAULT *graph.RenameVersionResp

func (p *RenameVersionResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(graph.RenameVersionResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *RenameVersionResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *RenameVersionResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *RenameVersionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RenameVersionResult) Unmarshal(in []byte) error {
	msg := new(graph.RenameVersionResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RenameVersionResult) GetSuccess() *graph.RenameVersionResp {
	if !p.IsSetSuccess() {
		return RenameVersionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RenameVersionResult) SetSuccess(x interface{}) {
	p.Success = x.(*graph.RenameVersionResp)
}

func (p *RenameVersionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RenameVersionResult) GetResult() interface{} {
	return p.Success
}

func listVersionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(graph.ListVersionReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(graph.GraphService).ListVersion(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListVersionArgs:
		success, err := handler.(graph.GraphService).ListVersion(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListVersionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListVersionArgs() interface{} {
	return &ListVersionArgs{}
}

func newListVersionResult() interface{} {
	return &ListVersionResult{}
}

type ListVersionArgs struct {
	Req *graph.ListVersionReq
}

func (p *ListVersionArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(graph.ListVersionReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListVersionArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListVersionArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListVersionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListVersionArgs) Unmarshal(in []byte) error {
	msg := new(graph.ListVersionReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListVersionArgs_Req_DEFAULT *graph.ListVersionReq

func (p *ListVersionArgs) GetReq() *graph.ListVersionReq {
	if !p.IsSetReq() {
		return ListVersionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListVersionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListVersionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListVersionResult struct {
	Success *graph.ListVersionResp
}

var ListVersionResult_Success_DEFAULT *graph.ListVersionResp

func (p *ListVersionResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(graph.ListVersionResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListVersionResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListVersionResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListVersionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListVersionResult) Unmarshal(in []byte) error {
	msg := new(graph.ListVersionResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListVersionResult) GetSuccess() *graph.ListVersionResp {
	if !p.IsSetSuccess() {
		return ListVersionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListVersionResult) SetSuccess(x interface{}) {
	p.Success = x.(*graph.ListVersionResp)
}

func (p *ListVersionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListVersionResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AddGraph(ctx context.Context, Req *graph.AddGraphReq) (r *graph.AddGraphResp, err error) {
	var _args AddGraphArgs
	_args.Req = Req
	var _result AddGraphResult
	if err = p.c.Call(ctx, "AddGraph", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteGraph(ctx context.Context, Req *graph.DeleteGraphReq) (r *graph.DeleteGraphResp, err error) {
	var _args DeleteGraphArgs
	_args.Req = Req
	var _result DeleteGraphResult
	if err = p.c.Call(ctx, "DeleteGraph", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateGraph(ctx context.Context, Req *graph.UpdateGraphReq) (r *graph.UpdateGraphResp, err error) {
	var _args UpdateGraphArgs
	_args.Req = Req
	var _result UpdateGraphResult
	if err = p.c.Call(ctx, "UpdateGraph", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetGraph(ctx context.Context, Req *graph.GetGraphReq) (r *graph.GetGraphResp, err error) {
	var _args GetGraphArgs
	_args.Req = Req
	var _result GetGraphResult
	if err = p.c.Call(ctx, "GetGraph", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListGraph(ctx context.Context, Req *graph.ListGraphReq) (r *graph.ListGraphResp, err error) {
	var _args ListGraphArgs
	_args.Req = Req
	var _result ListGraphResult
	if err = p.c.Call(ctx, "ListGraph", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) StartEdit(ctx context.Context, Req *graph.StartEditReq) (r *graph.StartEditResp, err error) {
	var _args StartEditArgs
	_args.Req = Req
	var _result StartEditResult
	if err = p.c.Call(ctx, "StartEdit", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Save(ctx context.Context, Req *graph.SaveReq) (r *graph.SaveResp, err error) {
	var _args SaveArgs
	_args.Req = Req
	var _result SaveResult
	if err = p.c.Call(ctx, "Save", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddGraphMessage(ctx context.Context, Req *graph.AddGraphMessageReq) (r *graph.AddGraphMessageResp, err error) {
	var _args AddGraphMessageArgs
	_args.Req = Req
	var _result AddGraphMessageResult
	if err = p.c.Call(ctx, "AddGraphMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListGraphMessage(ctx context.Context, Req *graph.ListGraphMessageReq) (r *graph.ListGraphMessageResp, err error) {
	var _args ListGraphMessageArgs
	_args.Req = Req
	var _result ListGraphMessageResult
	if err = p.c.Call(ctx, "ListGraphMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateVersion(ctx context.Context, Req *graph.CreateVersionReq) (r *graph.CreateVersionResp, err error) {
	var _args CreateVersionArgs
	_args.Req = Req
	var _result CreateVersionResult
	if err = p.c.Call(ctx, "CreateVersion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteVersion(ctx context.Context, Req *graph.DeleteVersionReq) (r *graph.DeleteVersionResp, err error) {
	var _args DeleteVersionArgs
	_args.Req = Req
	var _result DeleteVersionResult
	if err = p.c.Call(ctx, "DeleteVersion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RenameVersion(ctx context.Context, Req *graph.RenameVersionReq) (r *graph.RenameVersionResp, err error) {
	var _args RenameVersionArgs
	_args.Req = Req
	var _result RenameVersionResult
	if err = p.c.Call(ctx, "RenameVersion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListVersion(ctx context.Context, Req *graph.ListVersionReq) (r *graph.ListVersionResp, err error) {
	var _args ListVersionArgs
	_args.Req = Req
	var _result ListVersionResult
	if err = p.c.Call(ctx, "ListVersion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
